import { AVAILABLE, SHELL_DEFAULTS, type ShellCommand, unavailable } from "./contracts.ts";

/** Shell, focus, overlay, and viewport commands. */
export const APPLICATION_COMMANDS: readonly ShellCommand[] = [
  {
    id: "app.help",
    title: "Help",
    description: "Show every command, its key, and whether it is available.",
    context: "global",
    defaultBinding: "?",
    keywords: ["keys", "shortcuts", "bindings"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "observation",
    slash: [{ form: "/help" }],
    availability: () => AVAILABLE,
  },
  {
    id: "app.commandPalette",
    title: "Command palette",
    description: "Search commands by name and run one.",
    context: "global",
    defaultBinding: "ctrl+p",
    keywords: ["commands", "run", "search"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    slash: [{ form: "/commands" }],
    availability: () => AVAILABLE,
  },
  {
    id: "app.exit",
    title: "Exit",
    description: "Close the shell and restore the terminal. Press twice to confirm.",
    context: "global",
    defaultBinding: "ctrl+c",
    keywords: ["quit", "close", "leave"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    slash: [{ form: "/quit" }],
    confirmation: "focused",
    availability: () => AVAILABLE,
  },
  {
    id: "schedule.controls",
    title: "Schedule controls",
    description: "Inspect schedules and use /schedule JSON for explicit lifecycle controls.",
    context: "global",
    defaultBinding: null,
    keywords: ["schedule", "timer", "pause", "recurrence"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "external",
    slash: [{ form: "/schedule" }],
    argument: { kind: "text", hint: "JSON schedule action", maxBytes: 65536, required: false },
    availability: () => AVAILABLE,
  },
  {
    id: "peer.action",
    title: "Peer mailbox",
    description:
      "Show this session's peer endpoint, or send one bounded JSON action to the peer mailbox.",
    context: "global",
    defaultBinding: null,
    keywords: ["peer", "mailbox", "message", "endpoint"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "external",
    slash: [{ form: "/peer" }],
    argument: { kind: "text", hint: "JSON peer action", maxBytes: 65536, required: false },
    availability: () => AVAILABLE,
  },
  {
    id: "skills.list",
    title: "List skills",
    description: "List the skills this session can invoke, optionally filtered by name.",
    context: "global",
    defaultBinding: null,
    keywords: ["skills", "catalog", "list"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "observation",
    slash: [{ form: "/skills" }],
    argument: { kind: "text", hint: "filter [after N]", maxBytes: 256, required: false },
    availability: () => AVAILABLE,
  },
  {
    id: "extensions.suggestions",
    title: "Package suggestions",
    description:
      "List this session's verified package suggestions with their reasons, freshness and install state. Installs nothing.",
    context: "global",
    defaultBinding: null,
    keywords: ["suggestions", "packages", "marketplace", "extensions"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "observation",
    slash: [{ form: "/suggestions" }],
    argument: { kind: "none" },
    availability: () => AVAILABLE,
  },
  {
    id: "session.export",
    title: "Export session",
    description: "Preview a versioned session package and its artifact omissions before writing.",
    context: "global",
    defaultBinding: null,
    keywords: ["export", "history", "jsonl", "package"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/export" }],
    argument: {
      kind: "options",
      hint: "export action",
      options: [
        { value: "preview", operand: null },
        { value: "write", operand: { hint: "package name", required: true } },
      ],
    },
    availability: () => AVAILABLE,
  },
  {
    id: "compact.preview",
    title: "Preview history checkpoint",
    description: "Preview an admitted checkpoint with exact recovery references before applying.",
    context: "global",
    defaultBinding: null,
    keywords: ["compact", "history", "checkpoint"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/compact" }],
    argument: {
      kind: "options",
      hint: "checkpoint action",
      options: [
        { value: "preview", operand: null },
        {
          value: "apply",
          operand: { hint: "candidate id", required: false },
          timing: "safe-point",
        },
        { value: "inspect", operand: { hint: "candidate id", required: true } },
        {
          value: "restore",
          operand: { hint: "candidate id", required: true },
          timing: "safe-point",
        },
      ],
    },
    availability: () => AVAILABLE,
  },
  {
    id: "compact.apply",
    title: "Apply history checkpoint",
    description: "Apply the current session's inspected, unexpired checkpoint preview.",
    context: "global",
    defaultBinding: null,
    keywords: ["compact", "checkpoint", "apply"],
    ...SHELL_DEFAULTS,
    timing: "safe-point",
    effect: "mutation",
    availability: () => AVAILABLE,
  },
  {
    id: "compression.show",
    title: "Compression controls",
    description: "Inspect and configure Brief, Hush, and Loom in one interactive panel.",
    context: "global",
    defaultBinding: null,
    keywords: ["compression", "brief", "hush", "loom", "raw", "tokens"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    slash: [{ form: "/compression" }],
    availability: () => AVAILABLE,
  },
  {
    id: "brief.set",
    title: "Set Brief verbosity",
    description:
      "Set Brief response density (compact|balanced|detailed|auto|on|off) for upcoming turns.",
    context: "global",
    defaultBinding: null,
    keywords: ["brief", "verbosity", "compact", "style"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/brief" }],
    argument: {
      kind: "options",
      hint: "Brief mode",
      options: [
        { value: "compact", operand: null, timing: "safe-point" },
        { value: "balanced", operand: null, timing: "safe-point" },
        { value: "detailed", operand: null, timing: "safe-point" },
        { value: "auto", operand: null, timing: "safe-point" },
        { value: "on", operand: null, timing: "safe-point" },
        { value: "off", operand: null, timing: "safe-point" },
      ],
    },
    availability: () => AVAILABLE,
  },
  {
    id: "hush.set",
    title: "Set Hush output mode",
    description: "Turn automatic command-output reduction on or off for upcoming tool calls.",
    context: "global",
    defaultBinding: null,
    keywords: ["hush", "output", "raw", "command"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/hush" }],
    argument: {
      kind: "options",
      hint: "Hush state",
      options: [
        { value: "on", operand: null, timing: "safe-point" },
        { value: "off", operand: null, timing: "safe-point" },
      ],
    },
    availability: () => AVAILABLE,
  },
  {
    id: "loom.set",
    title: "Set Loom read mode",
    description: "Turn automatic large-read projection on or off for upcoming tool calls.",
    context: "global",
    defaultBinding: null,
    keywords: ["loom", "read", "raw", "file"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/loom" }],
    argument: {
      kind: "options",
      hint: "Loom state",
      options: [
        { value: "on", operand: null, timing: "safe-point" },
        { value: "off", operand: null, timing: "safe-point" },
      ],
    },
    availability: () => AVAILABLE,
  },
  {
    id: "app.cancel",
    title: "Cancel current work",
    description: "Ask the running operation to stop, without leaving the shell.",
    context: "global",
    defaultBinding: "escape",
    keywords: ["stop", "abort", "interrupt"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    availability: (state) =>
      state.hasRunningWork ? AVAILABLE : unavailable("nothing is running to cancel"),
  },
  {
    id: "focus.next",
    title: "Focus next region",
    description: "Move to the next region in reading order.",
    context: "global",
    defaultBinding: "tab",
    keywords: ["move", "region", "forward"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    availability: () => AVAILABLE,
  },
  {
    id: "focus.previous",
    title: "Focus previous region",
    description: "Move to the previous region in reading order.",
    context: "global",
    defaultBinding: "shift+tab",
    keywords: ["move", "region", "back"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    availability: () => AVAILABLE,
  },
  {
    id: "overlay.close",
    title: "Close overlay",
    description: "Close the open overlay and return focus where it was.",
    context: "overlay",
    defaultBinding: "escape",
    keywords: ["dismiss", "back", "escape"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    availability: (state) => (state.overlayOpen ? AVAILABLE : unavailable("no overlay is open")),
  },
  {
    id: "questions.reopen",
    title: "Show waiting questions",
    description: "Show a structured question you left without answering.",
    context: "global",
    defaultBinding: null,
    keywords: ["question", "answer", "reopen", "waiting"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    availability: (state) =>
      state.hasWaitingQuestions ? AVAILABLE : unavailable("no question is waiting"),
  },
  {
    id: "view.scrollUp",
    title: "Scroll up",
    description: "Move the view up by a bounded amount.",
    context: "scrollable",
    defaultBinding: "pageup",
    keywords: ["scroll", "up"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    availability: (state) =>
      state.hasScrollableContent ? AVAILABLE : unavailable("nothing is scrollable yet"),
  },
  {
    id: "view.scrollDown",
    title: "Scroll down",
    description: "Move the view down by a bounded amount.",
    context: "scrollable",
    defaultBinding: "pagedown",
    keywords: ["scroll", "down"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    availability: (state) =>
      state.hasScrollableContent ? AVAILABLE : unavailable("nothing is scrollable yet"),
  },
  {
    id: "view.top",
    title: "Go to top",
    description: "Move to the start of the view.",
    context: "scrollable",
    defaultBinding: "home",
    keywords: ["start", "beginning"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    availability: (state) =>
      state.hasScrollableContent ? AVAILABLE : unavailable("nothing is scrollable yet"),
  },
  {
    id: "view.bottom",
    title: "Go to bottom",
    description: "Move to the end of the view.",
    context: "scrollable",
    defaultBinding: "end",
    keywords: ["end", "latest"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    availability: (state) =>
      state.hasScrollableContent ? AVAILABLE : unavailable("nothing is scrollable yet"),
  },
  {
    id: "profile.inspect",
    title: "Working profile",
    description: "Inspect, preview and apply this session’s working profile.",
    context: "global",
    defaultBinding: null,
    keywords: ["profile", "configuration"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/profile" }],
    argument: {
      kind: "options",
      hint: "profile action",
      options: [
        { value: "inspect", operand: null },
        { value: "list", operand: null },
        { value: "use", operand: { hint: "profile id", required: true } },
        { value: "preview", operand: { hint: "profile id", required: true } },
        { value: "apply", operand: { hint: "candidate id", required: true }, timing: "safe-point" },
        { value: "reconcile", operand: null, timing: "safe-point" },
        { value: "workspace", operand: { hint: "profile id or reset", required: true } },
        { value: "default", operand: { hint: "profile id", required: true } },
        { value: "cancel", operand: null },
      ],
    },
    availability: () => AVAILABLE,
  },
  {
    id: "environment.inspect",
    title: "Scoped environment",
    description: "Inspect or explicitly reload this session's child environment.",
    context: "global",
    defaultBinding: null,
    keywords: ["env", "environment", "reload"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/env" }],
    argument: {
      kind: "options",
      hint: "environment action",
      options: [
        { value: "inspect", operand: null },
        { value: "reload", operand: null, timing: "safe-point" },
        { value: "cancel", operand: null },
      ],
    },
    availability: () => AVAILABLE,
  },
  {
    id: "model.settings",
    title: "Model roles",
    description: "Inspect and configure shared model role defaults and overrides.",
    context: "global",
    defaultBinding: null,
    keywords: ["model", "settings", "roles", "presets"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    slash: [
      { form: "/model" },
      { form: "/model roles" },
      { form: "/model configure" },
      { form: "/settings models" },
    ],
    availability: () => AVAILABLE,
  },
  {
    id: "model.routes",
    title: "Named model routes",
    description: "Inspect and manage approved destinations without submitting requests.",
    context: "global",
    defaultBinding: null,
    keywords: ["route", "models"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "interactive",
    slash: [{ form: "/model routes" }, { form: "/route" }],
    availability: () => AVAILABLE,
  },
  ...(
    [
      ["inspect", "/fast", "immediate", "observation"],
      ["fast", "/fast on", "safe-point", "mutation"],
      ["standard", "/fast off", "safe-point", "mutation"],
      ["reset", "/fast reset", "safe-point", "mutation"],
    ] as const
  ).map(
    ([action, form, timing, effect]): ShellCommand => ({
      id: `model.processing.${action}`,
      title: `Processing speed: ${action}`,
      description: "Main session processing preference; preserves model and thinking.",
      context: "global",
      defaultBinding: null,
      keywords: ["processing", "speed", "fast"],
      ...SHELL_DEFAULTS,
      timing,
      effect,
      slash: [{ form }],
      availability: () => AVAILABLE,
    }),
  ),
];
