import { plannedCommand, SHELL_DEFAULTS, type ShellCommand } from "./contracts.ts";

/**
 * Catalog commands whose owning issue has not delivered the action yet (#790).
 *
 * They stay discoverable, so `/goal` or `/tools` tells the user who owns it
 * instead of falling through to the model as prompt text, and they can never
 * run until their owner replaces the entry with a shipped one.
 */
export const PLANNED_COMMANDS: readonly ShellCommand[] = [
  plannedCommand({
    id: "status.show",
    title: "Session status",
    description: "Show the session, model, mode, context and running work at a glance.",
    keywords: ["status", "state", "session"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "observation",
    slash: [{ form: "/status" }],
    owner: "#739",
    reason: "the status view is not built yet",
  }),
  plannedCommand({
    id: "doctor.show",
    title: "Shell health checks",
    description: "Check configuration, providers and local data from inside the shell.",
    keywords: ["doctor", "health", "diagnose"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "observation",
    slash: [{ form: "/doctor" }],
    owner: "#739",
    reason: "shell health checks are not built yet; run falryn doctor",
  }),
  plannedCommand({
    id: "tools.inspect",
    title: "Capability inspector",
    description:
      "Inspect which capabilities are registered, available, disclosed, executable and projected.",
    keywords: ["tools", "capabilities", "inspect", "mcp"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "observation",
    slash: [{ form: "/tools" }],
    owner: "#192",
    reason: "the capability inspector is not reachable from the shell yet",
  }),
  plannedCommand({
    id: "permissions.show",
    title: "Permissions",
    description: "Show the policy and confirmations that apply to this session.",
    keywords: ["permissions", "policy", "confirmation"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "observation",
    slash: [{ form: "/permissions" }],
    owner: "#739",
    reason: "the permissions view is not built yet",
  }),
  plannedCommand({
    id: "provider.manage",
    title: "Provider connections",
    description: "Select, connect, refresh or disconnect provider connections.",
    keywords: ["provider", "login", "account", "credentials"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/provider" }, { form: "/login" }],
    owner: "#273",
    reason: "provider settings are not in the shell yet; use falryn provider",
  }),
  plannedCommand({
    id: "quota.show",
    title: "Provider allowances",
    description: "Show provider quota and allowance state.",
    keywords: ["quota", "allowance", "usage"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "observation",
    slash: [{ form: "/quota" }],
    owner: "#1027",
    reason: "quota actions are not built yet",
  }),
  plannedCommand({
    id: "session.rename",
    title: "Rename session",
    description: "Name or pin the current session.",
    keywords: ["session", "rename", "name", "pin"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/rename" }, { form: "/session rename" }],
    argument: { kind: "text", hint: "name", maxBytes: 256, required: false },
    owner: "#794",
    reason: "session naming is not built yet",
  }),
  plannedCommand({
    id: "goal.control",
    title: "Goals",
    description: "Show, create, update, pause, resume or cancel a durable goal.",
    keywords: ["goal", "objective", "work"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/goal" }],
    argument: {
      kind: "options",
      hint: "goal action",
      options: [
        { value: "show", operand: null },
        { value: "list", operand: null },
        { value: "create", operand: { hint: "goal", required: true }, timing: "queued" },
        { value: "update", operand: { hint: "goal id", required: true }, timing: "safe-point" },
        { value: "pause", operand: null, timing: "safe-point" },
        { value: "resume", operand: null, timing: "safe-point" },
        { value: "cancel", operand: null, timing: "safe-point" },
      ],
    },
    owner: "#797",
    reason: "durable goals are not built yet",
  }),
  plannedCommand({
    id: "loop.control",
    title: "Loops",
    description: "Start, inspect, pause, resume or cancel a bounded iterative loop.",
    keywords: ["loop", "iterate", "repeat"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/loop" }],
    argument: {
      kind: "options",
      hint: "loop action",
      options: [
        { value: "start", operand: { hint: "task", required: true }, timing: "queued" },
        { value: "status", operand: null },
        { value: "pause", operand: null, timing: "safe-point" },
        { value: "resume", operand: null, timing: "safe-point" },
        { value: "cancel", operand: null, timing: "safe-point" },
      ],
    },
    owner: "#797",
    reason: "bounded loops are not built yet",
  }),
  plannedCommand({
    id: "tasks.show",
    title: "Background tasks",
    description: "Show and control running and finished background tasks.",
    keywords: ["tasks", "background", "jobs"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "observation",
    slash: [{ form: "/tasks" }],
    owner: "#276",
    reason: "the task dashboard is not built yet",
  }),
  plannedCommand({
    id: "agents.show",
    title: "Agents",
    description: "Show delegated agents, workflows, budgets and joins.",
    keywords: ["agents", "delegate", "workflow"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "observation",
    slash: [{ form: "/agents" }],
    owner: "#276",
    reason: "the agent dashboard is not built yet",
  }),
  plannedCommand({
    id: "extensions.show",
    title: "Extensions",
    description: "Show extension health and controls, optionally filtered to one kind.",
    keywords: ["extensions", "mcp", "hooks", "plugins", "packages"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "observation",
    slash: [
      { form: "/extensions" },
      { form: "/mcp", fixedArgument: "mcp" },
      { form: "/hooks", fixedArgument: "hooks" },
      { form: "/plugins", fixedArgument: "plugins" },
    ],
    argument: {
      kind: "options",
      hint: "extension kind",
      options: [
        { value: "mcp", operand: null },
        { value: "skills", operand: null },
        { value: "hooks", operand: null },
        { value: "plugins", operand: null },
      ],
    },
    owner: "#274",
    reason: "the Extensions view is not built yet",
  }),
  plannedCommand({
    id: "checkpoint.create",
    title: "Create a restore point",
    description: "Record a durable restore point for the session and workspace.",
    keywords: ["checkpoint", "restore", "save"],
    ...SHELL_DEFAULTS,
    timing: "safe-point",
    effect: "mutation",
    slash: [{ form: "/checkpoint" }],
    owner: "#792",
    reason: "manual restore points are not built yet",
  }),
  plannedCommand({
    id: "undo.apply",
    title: "Undo",
    description: "Undo the last recorded change through its restore point.",
    keywords: ["undo", "revert", "restore"],
    ...SHELL_DEFAULTS,
    timing: "safe-point",
    effect: "mutation",
    confirmation: "focused",
    slash: [{ form: "/undo" }],
    owner: "#792",
    reason: "durable undo is not built yet",
  }),
  plannedCommand({
    id: "settings.open",
    title: "Settings",
    description: "Edit settings with their defaults, sources and validation.",
    keywords: ["settings", "configuration", "preferences"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "mutation",
    slash: [{ form: "/settings" }],
    owner: "#272",
    reason: "the settings editor is not built yet",
  }),
  plannedCommand({
    id: "advisor.consult",
    title: "Consult the advisor",
    description: "Ask the advisor model about the current work, with an optional focus.",
    keywords: ["advisor", "review", "second opinion"],
    ...SHELL_DEFAULTS,
    timing: "immediate",
    effect: "external",
    behavior: "insert",
    slash: [{ form: "/advisor" }],
    argument: { kind: "text", hint: "focus", maxBytes: 1024, required: false },
    owner: "#1216",
    reason: "advisor consultation is not built yet",
  }),
];
