/** Public contracts for this capability. Internal modules import their exact dependencies. */

export type {
  BriefComparisonArm,
  BriefComparisonInvalidReason,
  BriefComparisonMatch,
  BriefComparisonPair,
  BriefComparisonResult,
  BriefComparisonUsage,
  BriefComparisonVerdict,
  BriefComplexity,
  BriefDelivery,
  BriefDensity,
  BriefDetail,
  BriefDimensions,
  BriefDirectness,
  BriefError,
  BriefErrorCode,
  BriefInterface,
  BriefLayers,
  BriefNeed,
  BriefOmission,
  BriefPolicy,
  BriefPolicySource,
  BriefPresentation,
  BriefPreservedFact,
  BriefProjection,
  BriefReceipt,
  BriefRequest,
  BriefSelectionReason,
  BriefVerbosityDecision,
  BriefVerbosityLevel,
  BriefVerbosityMode,
} from "./brief.ts";
export {
  BRIEF_COMPARISON_INVALID_REASONS,
  BRIEF_COMPARISON_SCHEMA_VERSION,
  BRIEF_COMPARISON_VERDICTS,
  BRIEF_COMPLEXITIES,
  BRIEF_DELIVERIES,
  BRIEF_DENSITIES,
  BRIEF_DETAIL_LEVELS,
  BRIEF_DIRECTNESS_LEVELS,
  BRIEF_ERROR_CODES,
  BRIEF_INTERFACES,
  BRIEF_OMISSIONS,
  BRIEF_PLACEMENT,
  BRIEF_POLICY_SOURCES,
  BRIEF_PRESENTATIONS,
  BRIEF_PRESERVED_FACTS,
  BRIEF_SCHEMA_VERSION,
  BRIEF_SELECTION_REASONS,
  BRIEF_STRATEGY_VERSION,
  BRIEF_VERBOSITY_LEVELS,
  BRIEF_VERBOSITY_MODES,
  briefOutputTokenBudget,
  compareBriefPair,
  DEFAULT_BRIEF_MAX_BYTES,
  DEFAULT_BRIEF_NEED,
  DEFAULT_BRIEF_POLICY,
  decideBriefVerbosity,
  HARD_BRIEF_MAX_BYTES,
  isBriefPolicySource,
  isBriefVerbosityMode,
  MAX_BRIEF_GUIDANCE_BYTES,
  preservedFactsFromNeed,
  projectBrief,
  recordBriefDelivery,
  resolveBriefPolicy,
  selectBriefVerbosity,
} from "./brief.ts";
export type {
  CompactError,
  CompactFallbackReason,
  CompactModelFailure,
  CompactModelFailureCode,
  CompactModelKind,
  CompactModelPort,
  CompactModelRequest,
  CompactModelSuccess,
  CompactReduceInput,
  CompactReduceResult,
  CompactStrategy,
  CompactUse,
} from "./compact-model.ts";
export {
  COMPACT_FALLBACK_REASONS,
  COMPACT_MODEL_KINDS,
  COMPACT_MODEL_VERSION,
  COMPACT_STRATEGIES,
  COMPACT_USES,
  DEFAULT_COMPACT_MAX_BYTES,
  describeCompactError,
  HARD_COMPACT_MAX_BYTES,
  MAX_COMPACT_QUESTION_BYTES,
  reduceCompact,
} from "./compact-model.ts";
export type {
  CompressionEvalError,
  CompressionEvalErrorCode,
  CompressionEvalInput,
  CompressionEvalLane,
  CompressionEvalResult,
  CompressionEvalRun,
  CompressionEvalRunInput,
  CompressionFidelityVerdict,
  CompressionLatencyVerdict,
  CompressionRecoveryKind,
  CompressionTokenKind,
} from "./compression-eval.ts";
export {
  COMPRESSION_EVAL_LANES,
  COMPRESSION_EVAL_VERSION,
  COMPRESSION_FIDELITY_VERDICTS,
  COMPRESSION_LATENCY_VERDICTS,
  COMPRESSION_RECOVERY_KINDS,
  COMPRESSION_TOKEN_KINDS,
  DEFAULT_EVAL_LATENCY_BUDGET_MS,
  describeCompressionEvalError,
  evaluateCompression,
  evaluateCompressionRun,
  HARD_EVAL_LATENCY_BUDGET_MS,
  MAX_EVAL_OBSERVATIONS,
} from "./compression-eval.ts";
export type {
  HistoryCheckpoint,
  HistoryCheckpointInput,
  HistoryExpansion,
  HistoryFoldableKind,
  HistoryItemInput,
  HistoryItemKind,
  HistoryPreservedItem,
  HistoryRequiredKind,
  OverflowReason,
  OverflowRetry,
  OverflowRetryInput,
  WindowPreviewInput,
} from "./history-checkpoint.ts";
export {
  checkpointHistory,
  describeHistoryItemKind,
  HISTORY_CHECKPOINT_VERSION,
  HISTORY_FOLDABLE_KINDS,
  HISTORY_ITEM_KINDS,
  HISTORY_REQUIRED_KINDS,
  MAX_HISTORY_ITEM_BYTES,
  MAX_HISTORY_ITEMS,
  MAX_SKILL_INSTRUCTION_BYTES,
  OVERFLOW_REASONS,
  previewCompactForSmallerWindow,
  retryAfterOverflow,
} from "./history-checkpoint.ts";
export type {
  HushCommandIdentity,
  HushError,
  HushExpansion,
  HushFamily,
  HushFidelity,
  HushOmission,
  HushOmissionKind,
  HushPort,
  HushRequest,
  HushResult,
  HushStrategy,
} from "./hush.ts";
export {
  classifyFamily,
  classifyReducerId,
  createHushPort,
  DEFAULT_HUSH_REDUCED_BYTES,
  HUSH_FAMILIES,
  HUSH_FIDELITIES,
  HUSH_REDUCER_VERSION,
  HUSH_STRATEGIES,
  MAX_HUSH_REDUCED_BYTES,
  reduceHush,
  validateHushRequest,
} from "./hush.ts";
export type {
  LoomArtifactReadPlan,
  LoomCache,
  LoomCacheKey,
  LoomCacheStatus,
  LoomCommitInput,
  LoomError,
  LoomErrorCode,
  LoomHandle,
  LoomInvalidation,
  LoomManifest,
  LoomMember,
  LoomMemberBytes,
  LoomOmission,
  LoomProjectionKind,
  LoomProjectionRequest,
  LoomProjectionResult,
  LoomProjectionSource,
  LoomProtectedFact,
  LoomRetrievalPlan,
  LoomRetrieveInput,
  LoomSearchHit,
  LoomUnsupportedProjectionKind,
} from "./loom.ts";
export {
  commitLoomManifest,
  completeLoomRetrieval,
  createLoomCache,
  DEFAULT_LOOM_CACHE_ENTRIES,
  DEFAULT_LOOM_HEAD_BYTES,
  DEFAULT_LOOM_PROJECTION_MAX_BYTES,
  DEFAULT_LOOM_SEARCH_CONTEXT_BYTES,
  DEFAULT_LOOM_SEARCH_HITS,
  DEFAULT_LOOM_STRATEGY,
  DEFAULT_LOOM_TAIL_BYTES,
  describeLoomError,
  HARD_LOOM_CACHE_ENTRIES,
  HARD_LOOM_PROJECTION_MAX_BYTES,
  HARD_LOOM_SEARCH_HITS,
  LOOM_PROJECTION_KINDS,
  LOOM_UNSUPPORTED_PROJECTION_KINDS,
  MAX_LOOM_KEY_FIELD,
  MAX_LOOM_MEMBERS,
  MAX_LOOM_PROTECTED_FACT_BYTES,
  MAX_LOOM_PROTECTED_FACTS,
  MAX_LOOM_QUERY_BYTES,
  MAX_LOOM_SUMMARY_BYTES,
  planLoomRetrieval,
  retrieveLoomProjection,
} from "./loom.ts";
export type {
  StructuralError,
  StructuralFamily,
  StructuralFidelity,
  StructuralOmission,
  StructuralRange,
  StructuralReduceInput,
  StructuralReduceResult,
} from "./structural-reduce.ts";
export {
  DEFAULT_STRUCTURAL_MAX_BYTES,
  describeStructuralError,
  HARD_STRUCTURAL_MAX_BYTES,
  reduceStructural,
  STRUCTURAL_FAMILIES,
  STRUCTURAL_FIDELITIES,
  STRUCTURAL_REDUCER_VERSION,
} from "./structural-reduce.ts";
