/** Public contracts for this capability. Internal modules import their exact dependencies. */

export type {
  CreateDirectoryOutcome,
  FileKind,
  FileSystemError,
  FileSystemErrorCode,
  FileSystemOperation,
  FileSystemPort,
  FileWriteReceipt,
  InMemoryFileSystemOptions,
  InMemoryNode,
  LocalPath,
  LocalPathError,
  LocalPathErrorCode,
  PathEntry,
} from "./filesystem.ts";
export {
  baseName,
  createInMemoryFileSystem,
  isInside,
  joinPath,
  localPath,
  localPathTextError,
  MAX_LOCAL_PATH_LENGTH,
  parentPath,
  parseLocalPath,
  resolveLocalPath,
} from "./filesystem.ts";
export type {
  CompiledGlob,
  DiscoveryTruncation,
  GlobPatternErrorReason,
  ParsedWorkspaceDiscovery,
  WorkspaceDiscoveryError,
  WorkspaceDiscoveryKind,
  WorkspaceDiscoveryLimitName,
  WorkspaceDiscoveryLimits,
  WorkspaceDiscoveryResult,
} from "./workspace-glob.ts";
export {
  compileGlobPattern,
  compileGlobPatterns,
  DEFAULT_DISCOVERY_LIMITS,
  DEFAULT_MAX_DISCOVERY_MATCHES,
  describeWorkspaceDiscoveryError,
  globMatchesAny,
  HARD_MAX_DISCOVERY_MATCHES,
  HARD_MAX_WALK_DEPTH,
  HARD_MAX_WALK_ENTRIES,
  isExcludedByGlobs,
  kindAdmitted,
  MAX_GLOB_PATTERN_LENGTH,
  MAX_GLOB_PATTERNS,
  matchGlob,
  parseWorkspaceDiscoveryRequest,
} from "./workspace-glob.ts";
export type {
  IndexHitFreshness,
  IndexLifecycle,
  IndexQueryKind,
  IndexRecordKind,
  IndexTruncation,
  ParsedWorkspaceIndexQuery,
  WorkspaceIndexError,
  WorkspaceIndexGeneration,
  WorkspaceIndexHit,
  WorkspaceIndexLimitName,
  WorkspaceIndexPort,
  WorkspaceIndexQueryResult,
  WorkspaceIndexRecord,
  WorkspaceIndexWritePort,
} from "./workspace-index.ts";
export {
  compareIndexHits,
  createInMemoryWorkspaceIndex,
  DEFAULT_INDEX_LIMITS,
  DEFAULT_MAX_INDEX_MATCHES,
  describeWorkspaceIndexError,
  excerptIndexText,
  HARD_MAX_INDEX_MATCHES,
  INDEX_FRESHNESS,
  INDEX_LIFECYCLES,
  INDEX_QUERY_KINDS,
  INDEX_RECORD_KINDS,
  indexLifecycleQueryable,
  lifecycleQueryError,
  MAX_INDEX_EXCERPT,
  MAX_INDEX_GENERATION_ID_LENGTH,
  MAX_INDEX_GLOBS,
  MAX_INDEX_QUERY_LENGTH,
  parseWorkspaceIndexQuery,
  recordMatchesQuery,
} from "./workspace-index.ts";
export type {
  StructuralParserPort,
  WorkspaceIndexBuildError,
  WorkspaceIndexBuildLimits,
  WorkspaceIndexBuildReport,
  WorkspaceIndexBuildRequest,
  WorkspaceIndexBuildSource,
} from "./workspace-index-build.ts";
export {
  buildIndexGeneration,
  DEFAULT_INDEX_BUILD_LIMITS,
  extractIndexRecordsFromText,
  indexRecordKinds,
  languageIdFromLogical,
  MAX_INDEX_BUILD_FILE_BYTES,
  MAX_INDEX_BUILD_FILES,
  MAX_INDEX_BUILD_RECORDS,
  mergeLexicalWithStructuralSymbols,
  resolveSourceLanguageId,
  validateIndexBuildLimits,
  WORKSPACE_INDEX_SCHEMA,
} from "./workspace-index-build.ts";
export type {
  WorkspaceLayout,
  WorkspaceLayoutCatalog,
  WorkspaceLayoutCatalogEntry,
  WorkspaceLayoutCatalogError,
  WorkspaceLayoutDocumentError,
  WorkspaceLayoutName,
  WorkspaceLayoutRoot,
} from "./workspace-layout.ts";
export {
  DEFAULT_WORKSPACE_LAYOUT_LIST_LIMIT,
  describeWorkspaceLayoutDocumentError,
  isLegalWorkspaceLayoutName,
  layoutNameFromFileName,
  MAX_WORKSPACE_LAYOUT_CATALOG,
  MAX_WORKSPACE_LAYOUT_NAME_LENGTH,
  parseWorkspaceLayoutDocument,
  queryWorkspaceLayoutCatalog,
  serializeWorkspaceLayout,
  WORKSPACE_LAYOUT_DIRECTORY,
  WORKSPACE_LAYOUT_EXTENSION,
  WORKSPACE_LAYOUT_VERSION,
  workspaceLayoutFileName,
  workspaceLayoutFromSet,
  workspaceLayoutName,
  workspaceSetFromLayout,
} from "./workspace-layout.ts";
export type {
  WalkTruncation,
  WorkspaceEntry,
  WorkspaceEntryFailure,
  WorkspaceListingError,
  WorkspaceListingLimits,
  WorkspaceListResult,
  WorkspaceStatResult,
  WorkspaceWalkResult,
} from "./workspace-listing.ts";
export {
  compareWorkspaceEntries,
  DEFAULT_LISTING_LIMITS,
  DEFAULT_MAX_LIST_ENTRIES,
  DEFAULT_MAX_WALK_DEPTH,
  DEFAULT_MAX_WALK_ENTRIES,
  describeWorkspaceListingError,
  entryFromStat,
  isHiddenLogical,
  listingLimits,
} from "./workspace-listing.ts";
export type {
  MutationAffectedEntry,
  MutationTransport,
  OverwritePolicy,
  ParsedWorkspaceMutation,
  WorkspaceMutationError,
  WorkspaceMutationItem,
  WorkspaceMutationItemStatus,
  WorkspaceMutationLimitName,
  WorkspaceMutationLimits,
  WorkspaceMutationOperation,
  WorkspaceMutationPreview,
  WorkspaceMutationResult,
} from "./workspace-mutate.ts";
export {
  computeMutationPlanId,
  DEFAULT_MAX_MUTATION_DEPTH,
  DEFAULT_MAX_MUTATION_ENTRIES,
  DEFAULT_MUTATION_LIMITS,
  describeWorkspaceMutationError,
  destinationInsideSource,
  HARD_MAX_MUTATION_DEPTH,
  HARD_MAX_MUTATION_ENTRIES,
  MUTATION_OPERATIONS,
  MUTATION_TRANSPORTS,
  OVERWRITE_POLICIES,
  parseWorkspaceMutation,
} from "./workspace-mutate.ts";
export type {
  ParsedPatchChangedRegionRead,
  ParsedPatchHunk,
  ParsedPatchPlan,
  ParsedPatchTarget,
  PatchGitObservation,
  PatchGitUnavailableReason,
  PatchHunkApplyResult,
  PatchHunkPreview,
  PatchPolicy,
  WorkspacePatchApplied,
  WorkspacePatchChangedRegion,
  WorkspacePatchChangedRegionRead,
  WorkspacePatchError,
  WorkspacePatchItem,
  WorkspacePatchItemStatus,
  WorkspacePatchLimitName,
  WorkspacePatchLimits,
  WorkspacePatchPreview,
  WorkspacePatchRejected,
  WorkspacePatchResult,
  WorkspacePatchRollback,
  WorkspacePatchRollbackReason,
  WorkspacePatchRolledBack,
} from "./workspace-patch.ts";
export {
  applyPatchHunks,
  assessPatchGitStatus,
  computePatchPlanId,
  DEFAULT_MAX_PATCH_HUNK_LINES,
  DEFAULT_MAX_PATCH_HUNKS,
  DEFAULT_MAX_PATCH_TARGETS,
  DEFAULT_PATCH_LIMITS,
  describeWorkspacePatchError,
  digestOfPatchOldLines,
  gitPathForPatchTarget,
  HARD_MAX_PATCH_HUNK_LINES,
  HARD_MAX_PATCH_HUNKS,
  HARD_MAX_PATCH_TARGETS,
  hunkHeader,
  joinPatchedLines,
  linesForChangedRegion,
  MAX_CHANGED_REGION_LINES,
  MAX_CONFLICT_CONTEXT_LINES,
  NOT_ATTEMPTED_PATCH_ROLLBACK,
  PATCH_GIT_UNAVAILABLE_REASONS,
  parsePatchChangedRegionRead,
  parseWorkspacePatchPlan,
  resolvePatchHunkAddresses,
  summarizePatchRollback,
} from "./workspace-patch.ts";
export type { BoundWorkspacePath, WorkspacePathBindError } from "./workspace-path.ts";
export { bindWorkspacePath, describeWorkspacePathBindError } from "./workspace-path.ts";
export type {
  ByteRange,
  DecodedWorkspaceText,
  LineRange,
  NewlineStyle,
  NumberedLine,
  WorkspaceBytesRead,
  WorkspaceFileRead,
  WorkspaceReadCompleteness,
  WorkspaceReadContinuation,
  WorkspaceReadDiagnostic,
  WorkspaceReadEncoding,
  WorkspaceReadError,
  WorkspaceReadExpansion,
  WorkspaceReadFidelity,
  WorkspaceReadLimitName,
  WorkspaceReadLimits,
  WorkspaceReadManyItem,
  WorkspaceReadManyResult,
  WorkspaceReadRange,
  WorkspaceReadTarget,
} from "./workspace-read.ts";
export {
  applyByteRange,
  applyLineRange,
  DEFAULT_MAX_AGGREGATE_READ_BYTES,
  DEFAULT_MAX_EXPANSION_BYTES,
  DEFAULT_MAX_EXPANSION_CHUNK_BYTES,
  DEFAULT_MAX_FILE_BYTES,
  DEFAULT_READ_CONCURRENCY,
  DEFAULT_READ_LIMITS,
  decodeWorkspaceText,
  describeWorkspaceReadError,
  detectNewline,
  isBinaryText,
  MAX_READ_MANY_TARGETS,
  MAX_WORKSPACE_AGGREGATE_BYTES,
  MAX_WORKSPACE_EXPANSION_BYTES,
  MAX_WORKSPACE_EXPANSION_CHUNK_BYTES,
  MAX_WORKSPACE_FILE_BYTES,
  MAX_WORKSPACE_STALE_RETRIES,
  numberLines,
  parseReadLimits,
  readLimits,
  splitLines,
} from "./workspace-read.ts";
export type {
  ContextPack,
  ContextPackExpansion,
  ContextPackItem,
  ContextPackItemRole,
  ContextPackTruncation,
  EmbeddingCorpusGeneration,
  EmbeddingCorpusPort,
  EmbeddingDestination,
  EmbeddingNormalization,
  EmbeddingPort,
  EmbeddingQueryError,
  EmbeddingQueryResult,
  EmbeddingRecord,
  EmbeddingVector,
  ParsedWorkspaceRetrievalQuery,
  RetrievalConfidence,
  RetrievalFidelity,
  RetrievalHit,
  RetrievalHitTruncation,
  RetrievalScores,
  RetrievalSemanticState,
  ScoredIndexRecord,
  WorkspaceRetrievalError,
  WorkspaceRetrievalLimitName,
  WorkspaceRetrievalResult,
} from "./workspace-retrieval.ts";
export {
  assembleContextPack,
  compareRetrievalHits,
  containsQuery,
  cosineSimilarity,
  createInMemoryEmbeddingCorpus,
  createInMemoryEmbeddingPort,
  DEFAULT_MAX_PACK_ITEMS,
  DEFAULT_MAX_PACK_TOKENS,
  DEFAULT_MAX_RETRIEVAL_MATCHES,
  DEFAULT_RETRIEVAL_LIMITS,
  DIVERSITY_LINE_GAP,
  describeWorkspaceRetrievalError,
  diversifyHits,
  dominantConfidence,
  EMBEDDING_DESTINATIONS,
  EMBEDDING_NORMALIZATIONS,
  embeddingRecordKey,
  embeddingUsable,
  estimatedTokensForExcerpt,
  fidelityForFreshness,
  HARD_MAX_PACK_ITEMS,
  HARD_MAX_PACK_TOKENS,
  HARD_MAX_RETRIEVAL_MATCHES,
  MAX_HITS_PER_PATH,
  MAX_RETRIEVAL_GLOBS,
  MAX_RETRIEVAL_QUERY_LENGTH,
  PACK_ITEM_ROLES,
  parseWorkspaceRetrievalQuery,
  RETRIEVAL_CONFIDENCES,
  RETRIEVAL_FIDELITIES,
  RETRIEVAL_SEMANTIC_STATES,
  RRF_K,
  reciprocalRankFusion,
  SEMANTIC_BASELINE,
  scoreIndexRecords,
  TOKENS_PER_EXCERPT_CHAR,
} from "./workspace-retrieval.ts";
export type {
  CompiledSearchQuery,
  ParsedWorkspaceSearch,
  SearchTruncation,
  WorkspaceSearchEngine,
  WorkspaceSearchError,
  WorkspaceSearchFallbackReason,
  WorkspaceSearchKind,
  WorkspaceSearchLimitName,
  WorkspaceSearchLimits,
  WorkspaceSearchMatch,
  WorkspaceSearchResult,
} from "./workspace-search.ts";
export {
  compareSearchMatches,
  compileSearchQuery,
  DEFAULT_MAX_SEARCH_MATCHES,
  DEFAULT_SEARCH_FILE_BYTES,
  DEFAULT_SEARCH_LIMITS,
  DEFAULT_SEARCH_TIMEOUT_MS,
  describeWorkspaceSearchError,
  excerptLine,
  findMatchColumn,
  HARD_MAX_SEARCH_MATCHES,
  MAX_SEARCH_CONTEXT,
  MAX_SEARCH_LINE_EXCERPT,
  MAX_SEARCH_QUERY_LENGTH,
  parseWorkspaceSearchRequest,
} from "./workspace-search.ts";
export type {
  BindWorkspaceSetPathOptions,
  BoundWorkspaceSetPath,
  WorkspaceRootEntry,
  WorkspaceSet,
  WorkspaceSetBindError,
  WorkspaceSetError,
} from "./workspace-set.ts";
export {
  bindWorkspaceSetPath,
  createWorkspaceSet,
  describeWorkspaceSetBindError,
  describeWorkspaceSetError,
  isLegalWorkspaceRootName,
  MAX_WORKSPACE_ROOT_NAME_LENGTH,
  primaryWorkspaceRoot,
} from "./workspace-set.ts";
export type {
  ParsedWorkspaceWritePlan,
  ParsedWorkspaceWriteTarget,
  WorkspaceWriteApplied,
  WorkspaceWriteChangedRegion,
  WorkspaceWriteError,
  WorkspaceWriteItem,
  WorkspaceWriteItemStatus,
  WorkspaceWriteLimitName,
  WorkspaceWriteLimits,
  WorkspaceWriteOperation,
  WorkspaceWriteOverlapReason,
  WorkspaceWritePolicy,
  WorkspaceWriteRejected,
  WorkspaceWriteResult,
  WriteNewlinePolicy,
} from "./workspace-write.ts";
export {
  DEFAULT_MAX_WRITE_AGGREGATE_BYTES,
  DEFAULT_MAX_WRITE_BYTES,
  DEFAULT_MAX_WRITE_TARGETS,
  DEFAULT_WRITE_LIMITS,
  describeWorkspaceWriteError,
  encodeWriteText,
  HARD_MAX_WRITE_AGGREGATE_BYTES,
  HARD_MAX_WRITE_BYTES,
  HARD_MAX_WRITE_TARGETS,
  MAX_WRITE_REVISION_LENGTH,
  parseWorkspaceWritePlan,
  WRITE_NEWLINE_POLICIES,
  WRITE_OPERATIONS,
  WRITE_POLICIES,
  wholeFileChangedRegion,
} from "./workspace-write.ts";
