/** Public contracts for this capability. Internal modules import their exact dependencies. */

export type {
  BoundAnnotation,
  PostHookSettlement,
  PreHookSettlement,
  RecordedHookDecision,
  RegisteredToolHook,
  ToolHookAnnotations,
  ToolHookDecision,
  ToolHookDiagnostic,
  ToolHookEnvelope,
  ToolHookFailurePosture,
  ToolHookFn,
  ToolHookFollowUp,
  ToolHookPhase,
  ToolHookPoint,
  ToolHookPostDecision,
  ToolHookPreDecision,
  ToolHookRegistry,
  ToolHookRegistryError,
  ToolLifecycleFact,
} from "./tool-hooks.ts";
export {
  createToolHookRegistry,
  DEFAULT_TOOL_HOOK_TIMEOUT_MS,
  failurePostureForHookPoint,
  hooksForPoint,
  isRecursionDenied,
  isToolHookPoint,
  MAX_TOOL_HOOK_ANNOTATION_KEYS,
  MAX_TOOL_HOOK_ANNOTATION_VALUE_LENGTH,
  MAX_TOOL_HOOK_RECURSION_DEPTH,
  MAX_TOOL_HOOK_TIMEOUT_MS,
  MAX_TOOL_HOOKS_PER_POINT,
  orderToolHooks,
  phaseForHookPoint,
  settlePostHookDecisions,
  settlePreHookDecisions,
  TOOL_HOOK_PHASES,
  TOOL_HOOK_POINTS,
  TOOL_HOOK_SCHEMA_VERSION,
} from "./tool-hooks.ts";
export type {
  DispatchReadyInvocation,
  HostPlatform,
  RawToolInvocation,
  ToolValidateError,
  ValidateAndNormalizeOptions,
  ValidateAndNormalizeResult,
} from "./tool-invocation.ts";
export {
  describeToolValidateError,
  isToolValidateErrorCode,
  normalizeToolPathArgument,
  TOOL_INVOCATION_SCHEMA_VERSION,
  toBoundToolInvocation,
  validateAndNormalizeInvocations,
} from "./tool-invocation.ts";
export type {
  BindToolProposalsOptions,
  BindToolProposalsResult,
  BoundToolInvocation,
  ToolBindError,
  ToolCatalog,
  ToolDescriptor,
  ToolInvocationOutcome,
  ToolInvocationRecord,
  ToolInvocationResultMetadata,
  ToolProposal,
} from "./tool-pipeline.ts";
export {
  bindToolProposals,
  createToolCatalog,
  DEFAULT_MAX_CONCURRENT_TOOLS,
  DEFAULT_MAX_TOOL_CALLS_PER_ITERATION,
  DEFAULT_MAX_TOOL_LOOP_ITERATIONS,
  effectOfToolOutcome,
  foldToolEffects,
  isToolInvocationStatus,
  MAX_CONCURRENT_TOOLS,
  MAX_TOOL_CALLS_PER_ITERATION,
  MAX_TOOL_LOOP_ITERATIONS,
  TOOL_PIPELINE_SCHEMA_VERSION,
} from "./tool-pipeline.ts";
export type {
  ConfirmationPosture,
  EffectClassification,
  FocusedConfirmation,
  FocusedConfirmationOutcome,
  FocusedConfirmationRequest,
  PolicyAuthorizedInvocation,
  ToolPolicyDecision,
  ToolPolicyDenyCode,
  ToolPolicyDenyReason,
  ToolPolicyProfile,
} from "./tool-policy.ts";
export {
  authorizeToolInvocation,
  canonicalizeJson,
  classifyEffectForPolicy,
  confirmationInputFingerprint,
  createFocusedConfirmationRequest,
  DEFAULT_TOOL_POLICY_PROFILE,
  describeToolPolicyDenyReason,
  evaluateToolPolicy,
  isToolPolicyDenyCode,
  resolveFocusedConfirmation,
  TOOL_POLICY_SCHEMA_VERSION,
} from "./tool-policy.ts";
export type {
  ConcurrencyContract,
  PlatformConstraint,
  ProjectionContract,
  RegisterToolSchemas,
  ToolCapabilityKind,
  ToolIdentity,
  ToolIdentityError,
  ToolLimits,
  ToolManifest,
  ToolManifestDocument,
  ToolPlatformArch,
  ToolPlatformOs,
  ToolRegistry,
  ToolRegistryEntry,
  ToolRegistryError,
  ToolSource,
} from "./tool-registry.ts";
export {
  createToolRegistry,
  createToolRegistryEntry,
  DEFAULT_TOOL_DESCRIPTION_MAX_BYTES,
  DEFAULT_TOOL_MAX_INPUT_BYTES,
  DEFAULT_TOOL_MAX_OUTPUT_BYTES,
  decodeToolIdentity,
  defaultConcurrencyContract,
  defaultProjectionContract,
  defaultToolLimits,
  encodeToolIdentity,
  isToolCapabilityKind,
  isToolSource,
  MAX_TOOL_DESCRIPTION_BYTES,
  MAX_TOOL_MAX_INPUT_BYTES,
  MAX_TOOL_MAX_OUTPUT_BYTES,
  MAX_TOOL_REGISTRY_ENTRIES,
  parseToolManifestDocument,
  TOOL_CAPABILITY_KINDS,
  TOOL_PLATFORM_ARCHES,
  TOOL_PLATFORM_OSES,
  TOOL_REGISTRY_SCHEMA_VERSION,
  TOOL_SOURCES,
  validateToolIdentity,
} from "./tool-registry.ts";
export type {
  ArtifactRef,
  AssembleCapabilityResultInput,
  CapabilityResult,
  CapabilityResultStatus,
  ContainedProcessOutcome,
  DiagnosticRef,
  ModelToolResultView,
  TimingBreakdown,
  ToolResultProvenance,
} from "./tool-result.ts";
export {
  assembleCapabilityResult,
  projectCapabilityResult,
  TOOL_RESULT_SCHEMA_VERSION,
} from "./tool-result.ts";
export type {
  PlannedToolWork,
  ToolJoinPolicy,
  ToolScheduleError,
  ToolScheduleItem,
  ToolSchedulePlan,
  ToolScheduleRequest,
} from "./tool-schedule.ts";
export {
  describeToolScheduleError,
  isToolJoinPolicy,
  planToolSchedule,
  TOOL_JOIN_POLICIES,
  TOOL_SCHEDULE_SCHEMA_VERSION,
  toolRecordFromSchedulingResult,
  workUnitForAuthorized,
  workUnitIdForInvocation,
} from "./tool-schedule.ts";
