/** Public contracts for this capability. Internal modules import their exact dependencies. */

export type {
  BashCommandRequest,
  CommandMode,
  CommandOutcome,
  CommandRequest,
  CommandRunnerPort,
  DirectCommandRequest,
  StubCommandRunner,
} from "./process.ts";
export {
  COMMAND_MODES,
  commandMode,
  createStubCommandRunner,
  isAbsoluteCommandPath,
  MAX_COMMAND_ARGUMENTS,
  MAX_COMMAND_ENVIRONMENT_BYTES,
  MAX_COMMAND_ENVIRONMENT_ENTRIES,
  MAX_COMMAND_OUTPUT_BYTES,
  MAX_COMMAND_SCRIPT_BYTES,
} from "./process.ts";
export type {
  CapturePressure,
  ProcessCaptureArtifactRef,
  ProcessCaptureCollector,
  ProcessCaptureEncoding,
  ProcessCaptureError,
  ProcessCaptureEvent,
  ProcessCaptureExit,
  ProcessCaptureLimits,
  ProcessCaptureListener,
  ProcessCapturePort,
  ProcessCaptureReport,
  ProcessCaptureRequest,
  ProcessCaptureStop,
  ProcessCaptureValidationCode,
  ProcessStreamCapture,
  ProcessStreamName,
} from "./process-capture.ts";
export {
  createProcessCaptureCollector,
  DEFAULT_PROCESS_CAPTURE_ARTIFACT_BYTES,
  DEFAULT_PROCESS_CAPTURE_BYTES,
  DEFAULT_PROCESS_CAPTURE_INLINE_BYTES,
  DEFAULT_PROCESS_CAPTURE_LINE_BYTES,
  DEFAULT_PROCESS_CAPTURE_QUEUE_BYTES,
  describeProcessCaptureStop,
  invalidProcessCaptureRequest,
  MAX_PROCESS_CAPTURE_ARTIFACT_BYTES,
  MAX_PROCESS_CAPTURE_BYTES,
  MAX_PROCESS_CAPTURE_INLINE_BYTES,
  MAX_PROCESS_CAPTURE_LINE_BYTES,
  MAX_PROCESS_CAPTURE_QUEUE_BYTES,
  PROCESS_CAPTURE_ENCODINGS,
  PROCESS_STREAM_NAMES,
  processCaptureArtifactId,
  resolveProcessCaptureLimits,
  validateProcessCaptureRequest,
} from "./process-capture.ts";
export type {
  ManagedServiceAttachment,
  ManagedServiceError,
  ManagedServiceEvent,
  ManagedServiceExit,
  ManagedServiceIdlePolicy,
  ManagedServiceListener,
  ManagedServicePort,
  ManagedServiceReadiness,
  ManagedServiceReplay,
  ManagedServiceRequest,
  ManagedServiceRestartPolicy,
  ManagedServiceSnapshot,
  ManagedServiceState,
  ManagedServiceStopReport,
  ManagedServiceValidationCode,
  ManagedServiceWriteReport,
  PtyAttachment,
  PtyDimensions,
  PtyEncoding,
  PtyExit,
  PtyReplay,
  PtySessionError,
  PtySessionEvent,
  PtySessionListener,
  PtySessionPort,
  PtySessionRequest,
  PtySessionSnapshot,
  PtySessionState,
  PtySignal,
  PtySignalReport,
  PtyTerminationReport,
  PtyValidationCode,
  PtyWriteReport,
  PtyWriteStatus,
} from "./process-session.ts";
export {
  DEFAULT_PTY_COLUMNS,
  DEFAULT_PTY_ROWS,
  DEFAULT_PTY_TERMINAL_NAME,
  invalidManagedServiceRequest,
  invalidPtyRequest,
  MANAGED_SERVICE_STATES,
  MAX_MANAGED_SERVICE_IDLE_MS,
  MAX_MANAGED_SERVICE_MARKER_BYTES,
  MAX_MANAGED_SERVICE_PROTOCOL_LENGTH,
  MAX_MANAGED_SERVICE_READINESS_BYTES,
  MAX_MANAGED_SERVICE_REPLAY_BYTES,
  MAX_MANAGED_SERVICE_RESTART_WINDOW_MS,
  MAX_MANAGED_SERVICE_RESTARTS,
  MAX_MANAGED_SERVICE_SHUTDOWN_TIMEOUT_MS,
  MAX_MANAGED_SERVICE_WRITE_BYTES,
  MAX_MANAGED_SERVICES,
  MAX_PTY_BACKLOG_BYTES,
  MAX_PTY_SESSIONS,
  MAX_PTY_TERMINAL_NAME_LENGTH,
  MAX_PTY_WRITE_BYTES,
  MAX_RETAINED_MANAGED_SERVICES,
  MAX_RETAINED_PTY_SESSIONS,
  PTY_ENCODINGS,
  PTY_SESSION_STATES,
  PTY_TERMINATION_TIMEOUT_MS,
  PTY_WRITE_STATUSES,
  ptyDimensions,
  validateManagedServiceRequest,
  validatePtySessionRequest,
} from "./process-session.ts";
export type { ProcessKillStage, ProcessTreeCertainty, ProcessTreeCleanup } from "./process-tree.ts";
export {
  DEFAULT_PROCESS_TREE_GRACE_MS,
  MAX_PROCESS_TREE_GRACE_MS,
  nextProcessTreeKill,
  PROCESS_KILL_STAGES,
  PROCESS_TREE_CERTAINTIES,
  processTreeCleanupAfter,
} from "./process-tree.ts";
