/** Public contracts for this capability. Internal modules import their exact dependencies. */

export type {
  DapEventMessage,
  DapFrameDecodeError,
  DapFrameDecoder,
  DapMessage,
  DapRequest,
  DapResponse,
  DebugAdapterCapabilities,
  DebugAdapterError,
  DebugAdapterEvent,
  DebugAdapterFailureReason,
  DebugAdapterInitializeArguments,
  DebugAdapterInitializeResult,
  DebugAdapterKey,
  DebugAdapterLimits,
  DebugAdapterLimitsError,
  DebugAdapterLimitsInput,
  DebugAdapterSnapshot,
  DebugAdapterStartRequest,
  DebugAdapterState,
} from "./debug-adapter.ts";
export {
  createDapFrameDecoder,
  DEBUG_ADAPTER_FAILURE_REASONS,
  DEBUG_ADAPTER_PROTOCOL,
  DEBUG_ADAPTER_STATES,
  DEFAULT_DEBUG_ADAPTER_DISCONNECT_TIMEOUT_MS,
  DEFAULT_DEBUG_ADAPTER_INITIALIZE_TIMEOUT_MS,
  DEFAULT_DEBUG_ADAPTER_LIMITS,
  DEFAULT_DEBUG_ADAPTER_REQUEST_TIMEOUT_MS,
  debugAdapterLimits,
  describeDebugAdapterFailure,
  encodeDapFrame,
  MAX_DEBUG_ADAPTER_FRAME_BYTES,
  parseDebugAdapterInitializeResult,
  validateDebugAdapterStartRequest,
} from "./debug-adapter.ts";
export type {
  DebugCaptureError,
  DebugConfirmation,
  DebugConfirmationKind,
  DebugConfirmationRequest,
  DebugSessionArtifactDocument,
  DebugSessionArtifactRef,
} from "./debug-adapter-capture.ts";
export {
  buildDebugConfirmationRequest,
  buildDebugSessionArtifactDocument,
  bytesAsChunks,
  DEBUG_CONFIRMATION_KINDS,
  debugConfirmationFingerprint,
  debugSessionArtifactId,
  encodeDebugSessionArtifact,
  MAX_DEBUG_SESSION_ARTIFACT_BYTES,
  resolveDebugConfirmation,
} from "./debug-adapter-capture.ts";
export type {
  DebugAttachRequest,
  DebugBreakpoint,
  DebugCancelRequest,
  DebugDisconnectOutcome,
  DebugDisconnectRequest,
  DebugEvaluateContext,
  DebugEvaluateRequest,
  DebugEvaluateResult,
  DebugLaunchRequest,
  DebugOutputEvent,
  DebugScope,
  DebugSessionMode,
  DebugSessionSnapshot,
  DebugSetBreakpointsRequest,
  DebugSetBreakpointsResult,
  DebugSourceBreakpoint,
  DebugStackFrame,
  DebugStoppedInfo,
  DebugTargetExit,
  DebugTargetState,
  DebugTerminateRequest,
  DebugThread,
  DebugVariable,
  DebugVariableProjection,
} from "./debug-adapter-session.ts";
export {
  DEBUG_EVALUATE_CONTEXTS,
  emptyDebugSessionSnapshot,
  evaluateMayMutate,
  MAX_DEBUG_BREAKPOINT_SOURCES,
  MAX_DEBUG_BREAKPOINTS_PER_SOURCE,
  MAX_DEBUG_EVALUATE_EXPRESSION_LENGTH,
  MAX_DEBUG_OUTPUT_EVENTS,
  MAX_DEBUG_OUTPUT_TEXT_LENGTH,
  MAX_DEBUG_SCOPES,
  MAX_DEBUG_STACK_FRAMES,
  MAX_DEBUG_THREADS,
  MAX_DEBUG_VARIABLES,
  parseBreakpointsResponse,
  parseEvaluateResponse,
  parseOutputEventBody,
  parseScopesResponse,
  parseStackTraceResponse,
  parseStoppedEventBody,
  parseTargetExitEvent,
  parseThreadsResponse,
  parseVariablesResponse,
  projectEvaluateForModel,
  projectOutputForModel,
  projectVariableForModel,
  REDACTED_VALUE,
  validateCancelRequest,
  validateDisconnectRequest,
  validateEvaluateRequest,
  validateLaunchOrAttachConfiguration,
  validateSetBreakpointsRequest,
  validateTerminateRequest,
  variableNameLooksSensitive,
} from "./debug-adapter-session.ts";
