/** Public contracts for this capability. Internal modules import their exact dependencies. */

export type {
  AttachmentDescriptor,
  AttachmentKind,
  AttachmentStatus,
  IncludeTranscriptAttachmentResult,
  MentionKind,
  MentionSpan,
} from "./context-attachment.ts";
export {
  ATTACHMENT_KINDS,
  ATTACHMENT_STATUSES,
  alreadyIncludedAttachmentReason,
  attachmentKey,
  BLOCKING_ATTACHMENT_STATUSES,
  blockingAttachments,
  describeAttachmentStatus,
  describeAttachments,
  describeBlockingReason,
  findAttachmentByIdentity,
  includeTranscriptAttachment,
  isBlockingAttachment,
  MENTION_KINDS,
  moveAttachment,
  parseMentions,
  removeAttachment,
  transcriptAttachmentIdentity,
  upsertAttachment,
} from "./context-attachment.ts";
export type {
  ContextBudgetCharge,
  ContextBudgetDestination,
  ContextBudgetError,
  ContextBudgetErrorCode,
  ContextBudgetOmission,
  ContextBudgetOmissionReason,
  ContextBudgetPlan,
  ContextBudgetProfile,
  ContextBudgetProfileInput,
  ContextPressureAction,
  ContextPressureKind,
  ContextSourceClassLimit,
  ContextSourceClassLimitInput,
  InsufficientContext,
  InsufficientContextRecovery,
} from "./context-budget.ts";
export {
  applyContextBudget,
  CONTEXT_BUDGET_DESTINATIONS,
  CONTEXT_BUDGET_OMISSION_REASONS,
  CONTEXT_PRESSURE_ACTIONS,
  CONTEXT_PRESSURE_KINDS,
  DEFAULT_CONTEXT_MAX_ITEM_BYTES,
  DEFAULT_CONTEXT_MAX_ITEM_TOKENS,
  DEFAULT_CONTEXT_MAX_ITEMS,
  DEFAULT_CONTEXT_MAX_LATENCY_MS,
  DEFAULT_CONTEXT_MAX_TOTAL_BYTES,
  DEFAULT_CONTEXT_MAX_TOTAL_TOKENS,
  DEFAULT_CONTEXT_RESERVED_OUTPUT_TOKENS,
  DEFAULT_CONTEXT_RESERVED_TOOL_FRAMING_TOKENS,
  describeContextBudgetError,
  HARD_CONTEXT_MAX_ITEMS,
  HARD_CONTEXT_MAX_LATENCY_MS,
  HARD_CONTEXT_MAX_TOTAL_BYTES,
  HARD_CONTEXT_MAX_TOTAL_TOKENS,
  INSUFFICIENT_CONTEXT_RECOVERIES,
  parseContextBudgetProfile,
} from "./context-budget.ts";
export type {
  ComposedContextPack,
  ComposedContextPackItem,
  ContextComposeError,
  ContextComposeErrorCode,
  ContextComposeInput,
  ContextPackCitation,
  ContextPackOmission,
  ContextPackOmissionReason,
  ContextPackOmissionStage,
  ContextPackRole,
  ContextPackUncertainty,
} from "./context-compose.ts";
export {
  CONTEXT_PACK_EXCERPT_BYTES_PER_TOKEN,
  CONTEXT_PACK_OMISSION_STAGES,
  CONTEXT_PACK_ROLES,
  CONTEXT_PACK_UNCERTAINTIES,
  composeContextPack,
  DEFAULT_SUPPORT_EXCERPT_BYTES,
  describeContextComposeError,
  HARD_SUPPORT_EXCERPT_BYTES,
} from "./context-compose.ts";
export type {
  AdmitEvidenceOptions,
  EvidenceAdmissionError,
  EvidenceAdmissionErrorCode,
  EvidenceCandidate,
  EvidenceCandidateInput,
  EvidenceExpansionHandle,
  EvidenceFidelity,
  EvidenceFreshness,
  EvidencePayload,
  EvidencePayloadInput,
  EvidenceSourceKind,
  EvidenceTrust,
  ExactSourceHandle,
  ExactSourceHandleInput,
} from "./context-evidence.ts";
export {
  admitEvidenceCandidate,
  admitEvidenceCandidates,
  claimsExactSource,
  describeEvidenceAdmissionError,
  EVIDENCE_FIDELITIES,
  EVIDENCE_FRESHNESSES,
  EVIDENCE_SOURCE_KINDS,
  EVIDENCE_TRUSTS,
  MAX_EVIDENCE_BATCH,
  MAX_EVIDENCE_ESTIMATED_TOKENS,
  MAX_EVIDENCE_INLINE_BYTES,
  MAX_EVIDENCE_LINEAGE_STEP_LENGTH,
  MAX_EVIDENCE_LINEAGE_STEPS,
  MAX_EVIDENCE_ORIGIN_LENGTH,
  MAX_EVIDENCE_RELATIONSHIPS,
  MAX_EVIDENCE_RETRIEVAL_COST,
} from "./context-evidence.ts";
export type {
  ContextExpandArtifactSource,
  ContextExpandCache,
  ContextExpandCacheKey,
  ContextExpandCacheStatus,
  ContextExpandError,
  ContextExpandErrorCode,
  ContextExpandInlineSource,
  ContextExpandInput,
  ContextExpandInvalidation,
  ContextExpandResult,
  ContextExpandSource,
} from "./context-expand.ts";
export {
  createContextExpandCache,
  DEFAULT_CONTEXT_EXPAND_CACHE_ENTRIES,
  DEFAULT_CONTEXT_EXPAND_MAX_BYTES,
  DEFAULT_CONTEXT_EXPAND_STRATEGY,
  describeContextExpandError,
  expandContextEvidence,
  HARD_CONTEXT_EXPAND_CACHE_ENTRIES,
  HARD_CONTEXT_EXPAND_MAX_BYTES,
  MAX_CONTEXT_EXPAND_KEY_FIELD,
} from "./context-expand.ts";
export type {
  ContextBatchStatus,
  ContextConflict,
  ContextConflictReason,
  ContextInspectError,
  ContextInspectErrorCode,
  ContextInspectReport,
} from "./context-inspect.ts";
export {
  CONTEXT_BATCH_STATUSES,
  CONTEXT_CONFLICT_REASONS,
  DEFAULT_LONG_SESSION_CONVERSATION_ITEMS,
  describeContextInspectError,
  inspectContextEvidence,
} from "./context-inspect.ts";
export type {
  ContextRankError,
  ContextRankErrorCode,
  ContextRankedItem,
  ContextRankInput,
  ContextRankOmission,
  ContextRankOmissionReason,
  ContextRankPlan,
  ContextRankSignal,
} from "./context-rank.ts";
export {
  CONTEXT_RANK_OMISSION_REASONS,
  CONTEXT_RANK_SIGNALS,
  DEFAULT_CONTEXT_MAX_PER_ORIGIN,
  DEFAULT_CONTEXT_MAX_SELECTED,
  describeContextRankError,
  HARD_CONTEXT_MAX_PER_ORIGIN,
  HARD_CONTEXT_MAX_SELECTED,
  MAX_CONTEXT_RANK_EXPLANATION,
  MAX_CONTEXT_RANK_QUERY_LENGTH,
  rankAndSelectContext,
} from "./context-rank.ts";
export type {
  ComposedPromptRequest,
  ComposePromptError,
  ComposePromptInput,
  ComposePromptResult,
  PromptCompositionBudgets,
  PromptExclusion,
  PromptExclusionReason,
  PromptSectionInput,
  PromptSectionRole,
  PromptToolInput,
  RenderedPromptSection,
  RenderedPromptTool,
} from "./prompt-composition.ts";
export {
  composePromptRequest,
  DEFAULT_PROMPT_COMPOSITION_BUDGETS,
  DEFAULT_PROMPT_MAX_SECTION_TOKENS,
  DEFAULT_PROMPT_MAX_TOOL_DESCRIPTION_BYTES,
  DEFAULT_PROMPT_MAX_TOTAL_TOKENS,
  estimatePromptTokens,
  isPromptExclusionReason,
  isPromptSectionRole,
  MAX_PROMPT_SECTION_INPUTS,
  MAX_PROMPT_TOOL_INPUTS,
  PROMPT_COMPOSITION_SCHEMA_VERSION,
  PROMPT_EXCLUSION_REASONS,
  PROMPT_SECTION_ROLES,
  promptSectionRoleLabel,
} from "./prompt-composition.ts";
export type {
  EnhancementOutcome,
  EnhancementOutcomeKind,
  EnhancementPath,
  EnhancementRequest,
  NormalizedPromptDraft,
} from "./prompt-enhancement.ts";
export {
  describeEnhancement,
  ENHANCEMENT_OUTCOME_KINDS,
  ENHANCEMENT_PATHS,
  explainNormalization,
  normalizePromptDraft,
} from "./prompt-enhancement.ts";
