/** Public contracts for this capability. Internal modules import their exact dependencies. */

export type {
  ConfigurationAlias,
  ConfigurationDeprecation,
  ConfigurationIssue,
  ConfigurationIssueKind,
  ConfigurationIssueSeverity,
  ConfigurationKeyDescriptor,
  ConfigurationKeyPath,
  ConfigurationKeyPathError,
  ConfigurationKeyPathErrorCode,
  ConfigurationKeyResolution,
  ConfigurationLayerContext,
  ConfigurationLimit,
  ConfigurationMergeBehavior,
  ConfigurationRegistryPort,
  ConfigurationScope,
  ConfigurationSensitivity,
  ConfigurationSourceKind,
  ConfigurationUnit,
  ConfigurationValidationResult,
  ConfigurationValue,
  ConfigurationValues,
  ConfigurationValueType,
  CredentialReference,
  CredentialStoreKind,
  SensitiveValueRedactor,
} from "./configuration.ts";
export {
  blockingIssues,
  CONFIGURATION_SCOPES,
  CONFIGURATION_SENSITIVITIES,
  CONFIGURATION_SOURCE_KINDS,
  CONFIGURATION_UNITS,
  CONFIGURATION_VALUE_TYPES,
  CREDENTIAL_STORE_KINDS,
  configurationKeyPath,
  isBlockingIssue,
  isConfigurationScope,
  isUnlimited,
  MAX_CONFIGURATION_KEY_PATH_LENGTH,
  parseConfigurationKeyPath,
  scopeForSourceKind,
  UNLIMITED,
} from "./configuration.ts";
export type {
  ConfigurationChange,
  ConfigurationGenerationRecord,
  ConfigurationInspection,
  ConfigurationLoadOutcome,
  ConfigurationSource,
  InspectedValue,
  OverriddenValue,
  ParseFailure,
  SourceOutcome,
  SourcePosition,
  SourceReport,
  ValueProvenance,
} from "./configuration-source.ts";
export {
  CONFIGURATION_LAYER_ORDER,
  isUnreadSource,
  SOURCE_OUTCOMES,
  UNREAD_SOURCE_OUTCOMES,
} from "./configuration-source.ts";
