/** Public contracts for this capability. Internal modules import their exact dependencies. */

export type {
  BackupError,
  BackupInspection,
  BackupName,
  LocalDiagnostics,
  RestoreResult,
  UserBackup,
} from "./backup.ts";
export { backupName, MAX_BACKUP_NAME_LENGTH, userBackupFileName } from "./backup.ts";
export type {
  ClassBudget,
  ClassPressure,
  ClassUsage,
  DurabilityClass,
  FailedPath,
  LocalDataPlatform,
  LocalDataRoot,
  MeasurementCompleteness,
  OutOfScopeCategory,
  OwnershipClass,
  OwnershipRegistration,
  PlanId,
  PlannedAction,
  PlannedClass,
  PlannedReason,
  QuotaPressure,
  ReconciledEntry,
  ReconciliationReport,
  RegistrationError,
  RegistrationErrorCode,
  RemovalConfirmation,
  RemovalKind,
  RemovalOutcome,
  RemovalPlan,
  RemovalPosture,
  RemovalRefusal,
  ResolvedRoot,
  RetainedPath,
  RetentionPolicy,
  RetentionReason,
  RetentionReport,
  RootInspection,
  RootLayout,
  RootProvenance,
  RootStatus,
  RootStatusCode,
  RootViability,
  RootViabilityCode,
  TemporaryIngestOwner,
} from "./local-data.ts";
export {
  blocksLocalData,
  DURABILITY_CLASSES,
  isLocalDataRoot,
  isOwnershipClass,
  isPlanId,
  isRootUsable,
  LOCAL_DATA_PLATFORMS,
  LOCAL_DATA_ROOTS,
  OUT_OF_SCOPE_CATEGORIES,
  OWNERSHIP_CLASSES,
  PLANNED_ACTIONS,
  PLANNED_REASONS,
  QUOTA_PRESSURES,
  REMOVAL_POSTURES,
  RETENTION_REASONS,
  ROOT_STATUS_CODES,
  ROOT_VIABILITIES,
  ROOT_VIABILITY_CODES,
  TEMPORARY_INGEST_OWNERS,
} from "./local-data.ts";
export type {
  GcCandidate,
  GcCandidateKind,
  GcConfirmation,
  GcOmission,
  GcOutcome,
  GcPlan,
  GcPlanId,
  GcRefusal,
  GcRetainedCount,
  GcRetentionReason,
  ReachabilityGcError,
} from "./reachability-gc.ts";
export { GC_CANDIDATE_KINDS, GC_RETENTION_REASONS, isGcPlanId } from "./reachability-gc.ts";
export type {
  AppliedMigration,
  Migration,
  MigrationSetError,
  MigrationSetErrorCode,
  SqliteBindings,
  SqliteCloseReport,
  SqliteConnectionPort,
  SqliteFailure,
  SqliteFailureCode,
  SqliteOpener,
  SqliteOpenOptions,
  SqliteOpenReport,
  SqliteOperation,
  SqliteRow,
  SqliteRunOutcome,
  SqliteStatements,
  SqliteStoreError,
  SqliteStoreFailure,
  SqliteStoreOptions,
  SqliteStorePort,
  SqliteTransactionKind,
  SqliteValue,
  SqliteWriteOutcome,
} from "./sqlite.ts";
export {
  DEFAULT_BUSY_TIMEOUT_MS,
  INITIAL_SCHEMA_VERSION,
  isCleanClose,
  MAX_BUSY_TIMEOUT_MS,
  MAX_INTEGRITY_PROBLEMS,
  MAX_MIGRATION_NAME_LENGTH,
  MAX_MIGRATIONS,
  MAX_SQLITE_DETAIL_LENGTH,
  MIN_BUSY_TIMEOUT_MS,
  migrationChecksum,
  SQLITE_FAILURE_CODES,
  SQLITE_OPERATIONS,
  SQLITE_TRANSACTION_KINDS,
  SqliteWorkError,
} from "./sqlite.ts";
