/** File, search, and reusable output-transform command policies. */

import type { HushCatalogEntry } from "./contracts.ts";

export const FILE_COMMANDS = [
  {
    reducerId: "files.ls",
    family: "listing",
    projection: "ls",
    executables: ["ls"],
    examples: ["ls", "ls -la", "ls -R workspace"],
  },
  {
    reducerId: "files.tree",
    family: "listing",
    projection: "listing",
    executables: ["tree"],
    examples: ["tree", "tree -L 3"],
  },
  {
    reducerId: "files.find",
    family: "listing",
    projection: "listing",
    executables: ["find"],
    examples: ["find . -name '*.ts'"],
  },
  {
    reducerId: "files.read",
    family: "listing",
    projection: "read",
    executables: ["cat", "head", "bat"],
    examples: ["cat README.md", "head -20 src/main.ts", "bat src/main.ts"],
  },
  {
    reducerId: "files.tail",
    family: "log",
    projection: "log",
    executables: ["tail"],
    examples: ["tail -n 20 app.log"],
  },
  {
    reducerId: "files.rg",
    family: "search",
    projection: "search",
    executables: ["rg", "ripgrep"],
    examples: ["rg 'TODO' src"],
  },
  {
    reducerId: "files.grep",
    family: "search",
    projection: "search",
    executables: ["grep", "ag"],
    examples: ["grep -R TODO src"],
  },
  {
    reducerId: "files.diff",
    family: "listing",
    projection: "git-diff",
    executables: ["diff"],
    examples: ["diff before.ts after.ts"],
  },
  {
    reducerId: "files.count",
    family: "data",
    projection: "table",
    executables: ["wc"],
    examples: ["wc -l src/main.ts"],
  },
  {
    reducerId: "transform.structured",
    family: "data",
    projection: "structured",
    executables: ["json", "deps", "env"],
    examples: ["json package.json", "deps .", "env -f AWS"],
  },
  {
    reducerId: "transform.log",
    family: "log",
    projection: "log",
    executables: ["log", "journalctl"],
    examples: ["log app.log", "journalctl -u falryn"],
  },
  {
    reducerId: "transform.summary",
    family: "build",
    projection: "operation",
    executables: ["summary", "err"],
    examples: ["summary make", "err make"],
  },
  {
    reducerId: "test.generic",
    family: "test",
    projection: "test",
    executables: ["test"],
    examples: ["test custom-runner"],
  },
  {
    reducerId: "format.generic",
    family: "lint",
    projection: "diagnostic",
    executables: ["format", "lint"],
    examples: ["format --check .", "lint src"],
  },
  {
    reducerId: "build.generic",
    family: "build",
    projection: "build",
    executables: ["build"],
    examples: ["build"],
  },
] as const satisfies readonly HushCatalogEntry[];
