/** JavaScript and TypeScript command policies. */

import type { HushCatalogEntry } from "./contracts.ts";

export const JAVASCRIPT_COMMANDS = [
  {
    reducerId: "js.package",
    family: "package",
    projection: "package",
    executables: ["npm", "pnpm", "yarn", "npx", "pnpx"],
    examples: [
      "npm run custom",
      "npm exec custom",
      "pnpm install",
      "pnpm list",
      "pnpm outdated",
      "pnpm run custom",
      "npx custom-tool",
    ],
  },
  {
    reducerId: "js.typecheck",
    family: "typecheck",
    projection: "diagnostic",
    executables: ["tsc", "basedpyright", "ty"],
    examples: ["tsc --noEmit", "basedpyright", "ty check"],
  },
  {
    reducerId: "js.lint",
    family: "lint",
    projection: "diagnostic",
    executables: ["biome", "eslint", "oxlint"],
    examples: ["biome check .", "eslint src", "oxlint src"],
  },
  {
    reducerId: "js.format",
    family: "lint",
    projection: "diagnostic",
    executables: ["prettier"],
    examples: ["prettier --check ."],
  },
  {
    reducerId: "js.test",
    family: "test",
    projection: "test",
    executables: ["jest", "vitest", "playwright", "mocha"],
    examples: ["jest", "vitest run", "playwright test", "mocha"],
  },
  {
    reducerId: "js.build",
    family: "build",
    projection: "build",
    executables: ["next", "nx", "turbo"],
    examples: ["next build", "nx build app", "turbo build"],
  },
  {
    reducerId: "js.prisma",
    family: "build",
    projection: "operation",
    executables: ["prisma"],
    examples: [
      "prisma generate",
      "prisma migrate dev",
      "prisma migrate status",
      "prisma migrate deploy",
      "prisma db push",
    ],
  },
  {
    reducerId: "bun.test",
    family: "test",
    projection: "test",
    executables: ["bun"],
    examples: ["bun test"],
    matches: (tokens) => tokens[1] === "test",
  },
  {
    reducerId: "bun.build",
    family: "build",
    projection: "build",
    executables: ["bun"],
    examples: ["bun run build"],
    matches: (tokens) => tokens[1] === "run" && tokens[2] === "build",
  },
  {
    reducerId: "bun.lint",
    family: "lint",
    projection: "diagnostic",
    executables: ["bun"],
    examples: ["bun run check", "bun run lint"],
    matches: (tokens) => tokens[1] === "run" && (tokens[2] === "check" || tokens[2] === "lint"),
  },
  {
    reducerId: "bun.typecheck",
    family: "typecheck",
    projection: "diagnostic",
    executables: ["bun"],
    examples: ["bun run typecheck"],
    matches: (tokens) => tokens[1] === "run" && tokens[2] === "typecheck",
  },
  {
    reducerId: "bun.command",
    family: "package",
    projection: "package",
    executables: ["bun"],
    examples: ["bun install", "bun run custom"],
  },
] as const satisfies readonly HushCatalogEntry[];
