/** Language ecosystem command policies outside JavaScript and TypeScript. */

import type { HushCatalogEntry } from "./contracts.ts";

export const LANGUAGE_COMMANDS = [
  {
    reducerId: "rust.test",
    family: "test",
    projection: "test",
    executables: ["cargo"],
    examples: ["cargo test", "cargo nextest run"],
    matches: (tokens) => ["test", "nextest"].includes((tokens[1] ?? "").toLowerCase()),
  },
  {
    reducerId: "rust.diagnostic",
    family: "lint",
    projection: "diagnostic",
    executables: ["cargo", "clippy"],
    examples: ["cargo clippy", "cargo check", "cargo fmt --check", "clippy"],
    matches: (tokens) => ["check", "clippy", "fmt"].includes(tokens[1] ?? "clippy"),
  },
  {
    reducerId: "rust.build",
    family: "build",
    projection: "build",
    executables: ["cargo"],
    examples: ["cargo build", "cargo install ripgrep"],
  },
  {
    reducerId: "python.test",
    family: "test",
    projection: "test",
    executables: ["pytest"],
    examples: ["pytest", "python -m pytest"],
  },
  {
    reducerId: "python.diagnostic",
    family: "lint",
    projection: "diagnostic",
    executables: ["mypy", "ruff"],
    examples: ["mypy src", "python -m mypy src", "ruff check .", "ruff format --check ."],
  },
  {
    reducerId: "python.package",
    family: "package",
    projection: "package",
    executables: ["pip", "pip3", "uv", "poetry"],
    examples: [
      "pip list",
      "pip outdated",
      "pip install package",
      "pip show package",
      "uv pip install package",
      "uv run custom",
      "uv sync",
      "poetry install",
      "poetry lock",
      "poetry update",
    ],
  },
  {
    reducerId: "go.test",
    family: "test",
    projection: "test",
    executables: ["go"],
    examples: ["go test ./..."],
    matches: (tokens) => tokens[1] === "test",
  },
  {
    reducerId: "go.diagnostic",
    family: "lint",
    projection: "diagnostic",
    executables: ["go", "golangci-lint", "golangci"],
    examples: ["go vet ./...", "golangci-lint run", "golangci run"],
    matches: (tokens) => tokens[0] !== "go" || tokens[1] === "vet",
  },
  {
    reducerId: "go.build",
    family: "build",
    projection: "build",
    executables: ["go"],
    examples: ["go build ./..."],
  },
  {
    reducerId: "jvm.test",
    family: "test",
    projection: "test",
    executables: ["gradle", "gradlew", "mvn", "mvnw", "sbt"],
    examples: ["gradlew test", "mvn test", "mvn integration-test", "sbt test"],
    matches: (tokens) => tokens.some((token) => /test/i.test(token)),
  },
  {
    reducerId: "jvm.build",
    family: "build",
    projection: "build",
    executables: ["gradle", "gradlew", "mvn", "mvnw", "sbt"],
    examples: [
      "gradlew build",
      "gradlew dependencies",
      "mvn compile",
      "mvn package",
      "mvn install",
      "mvn verify",
      "mvn deploy",
      "sbt compile",
      "sbt run",
    ],
  },
  {
    reducerId: "dotnet.test",
    family: "test",
    projection: "test",
    executables: ["dotnet"],
    examples: ["dotnet test"],
    matches: (tokens) => tokens[1] === "test",
  },
  {
    reducerId: "dotnet.diagnostic",
    family: "lint",
    projection: "diagnostic",
    executables: ["dotnet"],
    examples: ["dotnet format"],
    matches: (tokens) => tokens[1] === "format",
  },
  {
    reducerId: "dotnet.build",
    family: "build",
    projection: "build",
    executables: ["dotnet"],
    examples: ["dotnet build", "dotnet restore"],
  },
  {
    reducerId: "apple.test",
    family: "test",
    projection: "test",
    executables: ["swift", "xcodebuild"],
    examples: ["swift test", "xcodebuild test"],
    matches: (tokens) => tokens.includes("test"),
  },
  {
    reducerId: "apple.build",
    family: "build",
    projection: "build",
    executables: ["swift", "xcodebuild"],
    examples: ["swift build", "xcodebuild build"],
  },
  {
    reducerId: "native.build",
    family: "build",
    projection: "build",
    executables: ["gcc", "g++", "pio", "quarto", "trunk"],
    examples: ["gcc main.c", "g++ main.cpp", "pio run", "quarto render", "trunk build"],
  },
  {
    reducerId: "elixir.diagnostic",
    family: "lint",
    projection: "diagnostic",
    executables: ["mix"],
    examples: ["mix format"],
    matches: (tokens) => tokens[1] === "format",
  },
  {
    reducerId: "elixir.build",
    family: "build",
    projection: "build",
    executables: ["mix"],
    examples: ["mix compile"],
  },
  {
    reducerId: "php.test",
    family: "test",
    projection: "test",
    executables: ["phpunit", "pest", "paratest"],
    examples: ["phpunit", "vendor/bin/pest", "vendor/bin/paratest"],
  },
  {
    reducerId: "php.diagnostic",
    family: "lint",
    projection: "diagnostic",
    executables: ["phpstan", "ecs", "pint"],
    examples: ["phpstan analyse src", "ecs check src", "pint --test"],
  },
  {
    reducerId: "php.command",
    family: "build",
    projection: "operation",
    executables: ["php"],
    examples: ["php artisan about", "php -l app.php"],
  },
  {
    reducerId: "ruby.test",
    family: "test",
    projection: "test",
    executables: ["rake", "rails", "rspec"],
    examples: ["rake test", "rails test", "bundle exec rspec"],
  },
  {
    reducerId: "ruby.diagnostic",
    family: "lint",
    projection: "diagnostic",
    executables: ["rubocop"],
    examples: ["bundle exec rubocop"],
  },
] as const satisfies readonly HushCatalogEntry[];
