/** Kubernetes/OpenShift corpus for the Hush projection scorecard. */

import type { ProjectionCase } from "./hush-projection-case.ts";

const NO_OMISSIONS = ["omitted", "…"] as const;

export const HUSH_KUBERNETES_CASES: readonly ProjectionCase[] = [
  {
    id: "kubernetes-kubectl-get-pods",
    projection: "table",
    executable: "kubectl",
    argv: ["get", "pods"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["falryn-api", "1/1", "Running", "falryn-worker", "1 (30s ago)", "5m"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-pods",
    projection: "table",
    executable: "kubectl",
    argv: ["pods"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["falryn-api", "Running", "falryn-worker", "1 (30s ago)"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-services",
    projection: "table",
    executable: "kubectl",
    argv: ["services"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["falryn", "10.96.0.42", "3000/TCP", "falryn-db", "10.96.0.84", "5432/TCP"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-get-pods-wide",
    projection: "table",
    executable: "kubectl",
    argv: ["get", "pods", "-o", "wide"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "falryn-api",
      "10.42.0.8",
      "worker-1",
      "falryn-worker",
      "10.42.0.11",
      "worker-2",
    ],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-oc-get-pods",
    projection: "table",
    executable: "oc",
    argv: ["get", "pods"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["falryn-api", "Running", "falryn-worker", "1 (30s ago)"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-oc-status",
    projection: "table",
    executable: "oc",
    argv: ["status"],
    rtkArgv: ["oc", "status"],
    competitiveTarget: "win",
    requiredMarkers: [
      "project falryn @ https://api.example:6443",
      "svc/falryn - 10.96.0.42:3000",
      ">deployment/falryn deploys image falryn:dev",
      "'oc describe <resource>/<name>'",
      "'oc get all -o yaml'",
    ],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-logs",
    projection: "log",
    executable: "kubectl",
    argv: ["logs", "falryn-api"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "2026-08-25Z",
      "12:00:00.001 service started",
      "12:00:01.125 request=req-736 status=ok",
      "12:00:02.250 request=req-784 status=ok",
    ],
    forbiddenMarkers: ["2026-08-25T", ...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-prefix-logs",
    projection: "log",
    executable: "kubectl",
    argv: ["logs", "deployment/falryn", "--all-pods", "--prefix"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "[pod/falryn-api/container/falryn] 2026-08-25Z",
      "12:00:01.125 request=req-736 status=ok",
      "[pod/falryn-worker/container/falryn] 2026-08-25Z",
      "12:00:02.250 request=req-784 status=ok",
    ],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-arbitrary-logs",
    projection: "log",
    executable: "kubectl",
    argv: ["logs", "plain"],
    baseline: "raw",
    requiredMarkers: ["ready\nready\nrequest=req-736 status=ok"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-oc-logs",
    projection: "log",
    executable: "oc",
    argv: ["logs", "falryn-api"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["2026-08-25Z", "service started", "req-736", "req-784"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-describe",
    projection: "operation",
    executable: "kubectl",
    argv: ["describe", "pod", "falryn-api", "-n", "falryn"],
    rtkArgv: ["kubectl", "describe", "pod", "falryn-api", "-n", "falryn"],
    competitiveTarget: "win",
    requiredMarkers: [
      "Name=falryn-api",
      "Namespace=falryn",
      "Labels=app=falryn",
      ">component=api",
      ">>Container ID=containerd://sha256:736abc784def",
      "Conditions",
      "Events",
      "Successfully assigned falryn/falryn-api to worker-1",
    ],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-apply",
    projection: "operation",
    executable: "kubectl",
    argv: ["apply", "-f", "app.yaml"],
    rtkArgv: ["kubectl", "apply", "-f", "app.yaml"],
    competitiveTarget: "win",
    requiredMarkers: [
      "configured deployment.apps/falryn",
      "service/falryn",
      "created configmap/falryn",
    ],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-create",
    projection: "operation",
    executable: "kubectl",
    argv: ["create", "namespace", "falryn"],
    rtkArgv: ["kubectl", "create", "namespace", "falryn"],
    competitiveTarget: "win",
    requiredMarkers: ["created namespace/falryn"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-delete",
    projection: "operation",
    executable: "kubectl",
    argv: ["delete", "pod", "falryn-old"],
    rtkArgv: ["kubectl", "delete", "pod", "falryn-old"],
    competitiveTarget: "win",
    requiredMarkers: ["deleted pod/falryn-old"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-rollout",
    projection: "operation",
    executable: "kubectl",
    argv: ["rollout", "status", "deployment/falryn"],
    rtkArgv: ["kubectl", "rollout", "status", "deployment/falryn"],
    competitiveTarget: "win",
    requiredMarkers: ["rolled-out deployment/falryn"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-scale",
    projection: "operation",
    executable: "kubectl",
    argv: ["scale", "deployment/falryn", "--replicas=3"],
    rtkArgv: ["kubectl", "scale", "deployment/falryn", "--replicas=3"],
    requiredMarkers: ["scaled deployment.apps/falryn"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-kubectl-auth",
    projection: "operation",
    executable: "kubectl",
    argv: ["auth", "can-i", "get", "pods"],
    rtkArgv: ["kubectl", "auth", "can-i", "get", "pods"],
    requiredMarkers: ["yes"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-oc-adm-top",
    projection: "operation",
    executable: "oc",
    argv: ["adm", "top", "pods"],
    rtkArgv: ["oc", "adm", "top", "pods"],
    competitiveTarget: "win",
    requiredMarkers: ["falryn-api", "25m", "96Mi", "falryn-worker", "12m", "64Mi"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "kubernetes-oc-adm-policy",
    projection: "operation",
    executable: "oc",
    argv: ["adm", "policy", "add-cluster-role-to-user", "admin", "falryn"],
    rtkArgv: ["oc", "adm", "policy", "add-cluster-role-to-user", "admin", "falryn"],
    requiredMarkers: ['clusterrole.rbac.authorization.k8s.io/admin added: "falryn"'],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
];
