/** HTTP and network corpus for the Hush projection scorecard. */

import type { ProjectionCase } from "./hush-projection-case.ts";

const COMPLETE = ["omitted", "…"] as const;

export const HUSH_NETWORK_CASES: readonly ProjectionCase[] = [
  {
    id: "curl-json",
    projection: "curl",
    executable: "curl",
    argv: ["https://example.test/status"],
    rtkArgv: ["curl", "https://example.test/status"],
    competitiveTarget: "win",
    requiredMarkers: ["req-736", "reducers", "82", "complete", "true"],
    forbiddenMarkers: ["% Total", "Dload", "1020", ...COMPLETE],
  },
  {
    id: "curl-headers-json",
    projection: "curl",
    executable: "curl",
    argv: ["-i", "https://example.test/headers"],
    rtkArgv: ["curl", "-i", "https://example.test/headers"],
    competitiveTarget: "win",
    requiredMarkers: [
      "HTTP/2 200",
      "content-type:application/json",
      'etag:"falryn-736"',
      "x-request-id:req-784",
      '"status":"ready"',
      '"reducers":82',
    ],
    forbiddenMarkers: ["% Total", "Dload", "\r", ...COMPLETE],
  },
  {
    id: "curl-events",
    projection: "curl",
    executable: "curl",
    argv: ["https://example.test/events"],
    rtkArgv: ["curl", "https://example.test/events"],
    competitiveTarget: "win",
    requiredMarkers: ["session req-736 opened", "heartbeat ready ×40", "done"],
    forbiddenMarkers: ["% Total", "Dload", ...COMPLETE],
  },
  {
    id: "curl-failure-body",
    projection: "curl",
    executable: "curl",
    argv: ["--fail-with-body", "https://example.test/missing"],
    baseline: "raw",
    competitiveTarget: "win",
    acceptedExitCodes: [22],
    requiredMarkers: ["not_found", "req-404", "recoverable", "false", "curl: (22)", "404"],
    forbiddenMarkers: ["% Total", "Dload", "1020", ...COMPLETE],
  },
  {
    id: "wget-download",
    projection: "wget",
    executable: "wget",
    argv: ["https://example.test/releases/falryn.tar.gz"],
    rtkArgv: ["wget", "https://example.test/releases/falryn.tar.gz"],
    competitiveTarget: "win",
    requiredMarkers: ["200", "example.test/releases/falryn.tar.gz", "falryn.tar.gz", "1.5KB"],
    forbiddenMarkers: ["Resolving", "Connecting", "100%", "saved [", ...COMPLETE],
  },
  {
    id: "wget-explicit-output",
    projection: "wget",
    executable: "wget",
    argv: ["-O", "falryn-release.tar.gz", "https://example.test/releases/falryn.tar.gz"],
    rtkArgv: ["wget", "-O", "falryn-release.tar.gz", "https://example.test/releases/falryn.tar.gz"],
    competitiveTarget: "win",
    requiredMarkers: [
      "200",
      "example.test/releases/falryn.tar.gz",
      "falryn-release.tar.gz",
      "1.5KB",
    ],
    forbiddenMarkers: ["Resolving", "Connecting", "100%", "saved [", ...COMPLETE],
  },
  {
    id: "wget-stdout-json",
    projection: "wget",
    executable: "wget",
    argv: ["-O", "-", "https://example.test/data.json"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["item-0", '"value":0', "item-29", '"value":29', '"next":null'],
    forbiddenMarkers: ["first 10 lines", "+", "100%", ...COMPLETE],
  },
  {
    id: "wget-redirect",
    projection: "wget",
    executable: "wget",
    argv: ["https://example.test/latest"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "302 Found",
      "Location: https://cdn.example.test/releases/falryn.tar.gz [following]",
      "200 OK",
      "falryn.tar.gz",
      "1536/1536",
    ],
    forbiddenMarkers: ["100%", ...COMPLETE],
  },
  {
    id: "wget-failure",
    projection: "wget",
    executable: "wget",
    argv: ["https://example.test/missing"],
    baseline: "raw",
    competitiveTarget: "win",
    acceptedExitCodes: [8],
    requiredMarkers: ["404 Not Found", "ERROR 404: Not Found."],
    forbiddenMarkers: ["100%", ...COMPLETE],
  },
  networkCase(
    "ping-darwin",
    "ping",
    ["-c", "3", "example.test"],
    [
      "ping example.test ip=192.0.2.80 data=56B",
      "reply seq=0",
      "reply seq=2",
      "sent=3 received=3 loss=0.0%",
      "stddev=0.516ms",
    ],
    true,
    "raw",
  ),
  networkCase(
    "ping-linux",
    "ping",
    ["-c", "3", "linux.example.test"],
    [
      "ping linux.example.test ip=192.0.2.81 data=56B wire=84B",
      "reply seq=1",
      "Request timeout for icmp_seq 2",
      "reply seq=3",
      "sent=3 received=2 loss=33.3333% time=2002ms",
      "mdev=0.450ms",
    ],
    true,
    "raw",
  ),
  networkCase(
    "rsync-transfer",
    "rsync",
    ["-av", "--progress", "src/", "backup/"],
    [
      "src/",
      "path\tbytes\t%\trate\telapsed\txfr\tremaining",
      "src/context.ts\t4096\t100\t4.00MB/s\t0:00:00\t1\t1/3",
      "src/hush.ts\t8192\t100\t8.00MB/s\t0:00:00\t2\t0/3",
      "sent=12736B received=84B rate=25640.00B/s",
      "total=12288B speedup=0.96",
    ],
    true,
    "raw",
  ),
  networkCase(
    "rsync-dry-run",
    "rsync",
    ["-ani", "--delete", "src/", "backup/"],
    [
      "created-dir backup",
      ">f+++++++++ src/new.ts",
      ">f.st...... src/changed.ts",
      "*deleting   src/obsolete.ts",
      "sent=736B received=42B rate=1556.00B/s",
      "total=784B speedup=1.01",
    ],
    true,
    "raw",
  ),
  networkCase(
    "ssh-json",
    "ssh",
    ["example.test", "falryn", "status", "--json"],
    ["example.test", '"status":"ready"', "req-736", '"reducers":82', '"complete":true'],
    true,
  ),
  networkCase(
    "ssh-text",
    "ssh",
    ["example.test", "falryn", "status"],
    ["host example.test", "status ready", "session req-736", "reducers 82"],
    false,
  ),
];

function networkCase(
  id: string,
  executable: "ping" | "rsync" | "ssh",
  argv: readonly string[],
  requiredMarkers: readonly string[],
  win: boolean,
  baseline: "raw" | "rtk" = "rtk",
): ProjectionCase {
  return {
    id,
    projection: "network",
    executable,
    argv,
    ...(baseline === "raw" ? { baseline: "raw" as const } : { rtkArgv: [executable, ...argv] }),
    ...(win ? { competitiveTarget: "win" as const } : {}),
    requiredMarkers,
    forbiddenMarkers: [...COMPLETE],
  };
}
