/** Build and operation corpus for the Hush projection scorecard. */

import type { ProjectionCase } from "./hush-projection-case.ts";

const NO_OMISSIONS = ["omitted", "…"] as const;

export const HUSH_BUILD_OPERATION_CASES = [
  {
    id: "operation-err",
    projection: "operation",
    executable: "err",
    argv: ["build", "--fail"],
    rtkArgv: ["err", "build", "--fail"],
    competitiveTarget: "win",
    acceptedExitCodes: [1],
    requiredMarkers: [
      "1 error, 1 warning",
      "src/runtime.ts:14:6 error[BUILD001]: Missing provider route.",
      "src/router.ts:28:3 warning[BUILD002]: Fallback route is not explicit.",
    ],
    forbiddenMarkers: ["2 issues (", ...NO_OMISSIONS],
  },
  {
    id: "build-generic",
    projection: "build",
    executable: "build",
    argv: [],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "ok dist/falryn 1.2MB 420ms",
      "steps 3: compile context engine, bundle runtime, write manifest",
    ],
    forbiddenMarkers: ["Build step", "Build complete", ...NO_OMISSIONS],
  },
  {
    id: "build-next",
    projection: "build",
    executable: "next",
    argv: ["build"],
    rtkArgv: ["next", "build"],
    competitiveTarget: "win",
    requiredMarkers: ["ok next 15.4.0 4.2s", "○ / 5.2kB/102kB", "ƒ /api/context 0B/97kB"],
    forbiddenMarkers: ["Creating an optimized", "Collecting page", ...NO_OMISSIONS],
  },
  {
    id: "build-nx",
    projection: "build",
    executable: "nx",
    argv: ["build", "falryn"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["ok nx falryn:build 2.1s -> dist/apps/falryn"],
    forbiddenMarkers: ["NX Running", "Successfully ran", ...NO_OMISSIONS],
  },
  {
    id: "build-turbo",
    projection: "build",
    executable: "turbo",
    argv: ["build"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "ok turbo 2/2 1.2s cache 0/2",
      "packages @falryn/app,@falryn/core",
      "@falryn/core -> dist/core.js",
      "@falryn/app -> dist/app.js",
    ],
    forbiddenMarkers: ["cache miss", "Remote caching", ...NO_OMISSIONS],
  },
  {
    id: "operation-prisma-generate",
    projection: "operation",
    executable: "prisma",
    argv: ["generate"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "ok prisma generate Prisma Client@6.14.0 123ms prisma/schema.prisma -> ./node_modules/@prisma/client",
    ],
    forbiddenMarkers: ["Environment variables", "Start by importing", ...NO_OMISSIONS],
  },
  {
    id: "operation-prisma-migrate",
    projection: "operation",
    executable: "prisma",
    argv: ["migrate", "dev"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "ok prisma migrate dev 20260825_add_context_receipts",
      "prisma/schema.prisma",
      'SQLite database "dev.db" at "file:./dev.db"',
    ],
    forbiddenMarkers: ["Environment variables", "following migration", ...NO_OMISSIONS],
  },
  {
    id: "operation-prisma-status",
    projection: "operation",
    executable: "prisma",
    argv: ["migrate", "status"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["ok prisma migrate status 12 migrations", "prisma/schema.prisma"],
    forbiddenMarkers: ["Environment variables", "Database schema is up", ...NO_OMISSIONS],
  },
  {
    id: "operation-prisma-db-push",
    projection: "operation",
    executable: "prisma",
    argv: ["db", "push"],
    rtkArgv: ["prisma", "db", "push"],
    competitiveTarget: "win",
    requiredMarkers: ["ok prisma db push 84ms", "prisma/schema.prisma"],
    forbiddenMarkers: ["Environment variables", "Your database is now", ...NO_OMISSIONS],
  },
  {
    id: "operation-prisma-validate",
    projection: "operation",
    executable: "prisma",
    argv: ["validate"],
    rtkArgv: ["prisma", "validate"],
    competitiveTarget: "win",
    requiredMarkers: ["ok prisma validate prisma/schema.prisma"],
    forbiddenMarkers: ["Environment variables", "valid 🚀", ...NO_OMISSIONS],
  },
  {
    id: "build-bun",
    projection: "build",
    executable: "bun",
    argv: ["run", "build"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["ok bun 42 modules 48ms", "dist/falryn.js 1.2MB"],
    forbiddenMarkers: ["$ bun build", "Bundled", ...NO_OMISSIONS],
  },
  {
    id: "build-cargo",
    projection: "build",
    executable: "cargo",
    argv: ["build", "--release"],
    rtkArgv: ["cargo", "build", "--release"],
    competitiveTarget: "win",
    requiredMarkers: ["ok cargo release 0.42s", "serde@1.0.219", "falryn@0.3.0"],
    forbiddenMarkers: ["Compiling", "Finished", ...NO_OMISSIONS],
  },
  {
    id: "build-cargo-install",
    projection: "build",
    executable: "cargo",
    argv: ["install", "hush-cli"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["ok installed hush-cli@0.3.0 4.2s -> /workspace/.cargo/bin/hush; compiled 2"],
    forbiddenMarkers: ["Updating", "Downloaded", "Compiling", ...NO_OMISSIONS],
  },
  {
    id: "build-go",
    projection: "build",
    executable: "go",
    argv: ["build", "./..."],
    rtkArgv: ["go", "build", "./..."],
    requiredMarkers: [],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "build-gradle",
    projection: "build",
    executable: "gradle",
    argv: ["build"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "ok gradle build 2s 4/4 tasks",
      "ran 4: :compileJava, :processResources, :classes, :jar",
    ],
    forbiddenMarkers: ["> Task", "BUILD SUCCESSFUL", ...NO_OMISSIONS],
  },
  {
    id: "build-gradlew",
    projection: "build",
    executable: "gradlew",
    argv: ["build"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["ok gradle build 2s 4/4 tasks", ":compileJava"],
    forbiddenMarkers: ["> Task", "BUILD SUCCESSFUL", ...NO_OMISSIONS],
  },
  {
    id: "build-mvn-compile",
    projection: "build",
    executable: "mvn",
    argv: ["compile"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["ok maven compile falryn-core@0.3.0 jar 1.42s"],
    forbiddenMarkers: ["[INFO]", "BUILD SUCCESS", ...NO_OMISSIONS],
  },
  {
    id: "build-mvnw-package",
    projection: "build",
    executable: "mvnw",
    argv: ["package"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["ok maven package falryn-core@0.3.0 jar 1.42s"],
    forbiddenMarkers: ["[INFO]", "BUILD SUCCESS", ...NO_OMISSIONS],
  },
  ...["install", "verify", "deploy"].map(
    (action) =>
      ({
        id: `build-mvn-${action}`,
        projection: "build",
        executable: "mvn",
        argv: [action],
        baseline: "raw",
        competitiveTarget: "win",
        requiredMarkers: [`ok maven ${action} falryn-core@0.3.0 jar 1.42s`],
        forbiddenMarkers: ["[INFO]", "BUILD SUCCESS", ...NO_OMISSIONS],
      }) as const,
  ),
  ...["compile", "run"].map(
    (action) =>
      ({
        id: `build-sbt-${action}`,
        projection: "build",
        executable: "sbt",
        argv: [action],
        ...(action === "compile" ? { baseline: "raw" as const } : { rtkArgv: ["sbt", action] }),
        competitiveTarget: "win",
        requiredMarkers: [`ok sbt ${action} 2s v1.10.0 42 sources`],
        forbiddenMarkers: ["[info]", "[success]", ...NO_OMISSIONS],
      }) as const,
  ),
  {
    id: "build-dotnet",
    projection: "build",
    executable: "dotnet",
    argv: ["build"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "ok dotnet 00:00:01.42 0W 0E restored 1",
      "Falryn -> /workspace/bin/Release/net10.0/Falryn.dll",
    ],
    forbiddenMarkers: ["Determining projects", "Build succeeded", ...NO_OMISSIONS],
  },
  {
    id: "build-dotnet-restore",
    projection: "build",
    executable: "dotnet",
    argv: ["restore"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "ok restore 2",
      "/workspace/Falryn.csproj 142ms",
      "/workspace/Falryn.Tests.csproj 184ms",
    ],
    forbiddenMarkers: ["Determining projects", "Restored ", ...NO_OMISSIONS],
  },
  {
    id: "build-swift",
    projection: "build",
    executable: "swift",
    argv: ["build", "-c", "release"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "ok swift production 0.42s 4 steps",
      "Compiling Falryn main.swift",
      "Linking falryn",
    ],
    forbiddenMarkers: ["Building for production", "Build complete", ...NO_OMISSIONS],
  },
  {
    id: "build-xcodebuild",
    projection: "build",
    executable: "xcodebuild",
    argv: ["build", "-scheme", "Falryn"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "ok xcode Falryn/Falryn",
      "CompileSwift normal arm64 /workspace/Sources/Falryn.swift",
      "Ld /workspace/build/Release/Falryn normal arm64",
    ],
    forbiddenMarkers: ["Command line invocation", "BUILD SUCCEEDED", ...NO_OMISSIONS],
  },
  ...["gcc", "g++"].map(
    (executable) =>
      ({
        id: `build-${executable === "g++" ? "gpp" : executable}`,
        projection: "build",
        executable,
        argv: [executable === "gcc" ? "main.c" : "main.cpp", "-o", "falryn"],
        baseline: "raw",
        competitiveTarget: "win",
        requiredMarkers: [
          `W[-Wunused-variable] ${executable === "gcc" ? "main.c" : "main.cpp"}:14:6 unused variable 'context'`,
        ],
        forbiddenMarkers: ["warning:", ...NO_OMISSIONS],
      }) as const,
  ),
  {
    id: "build-pio",
    projection: "build",
    executable: "pio",
    argv: ["run"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["ok pio native 1.23seconds -> .pio/build/native/program", "RAM", "Flash"],
    forbiddenMarkers: ["Verbose mode", "SUCCESS]", ...NO_OMISSIONS],
  },
  {
    id: "build-quarto",
    projection: "build",
    executable: "quarto",
    argv: ["render"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["ok quarto docs/index.qmd -> _site/index.html (html)"],
    forbiddenMarkers: ["pandoc index", "Output created", ...NO_OMISSIONS],
  },
  {
    id: "build-trunk",
    projection: "build",
    executable: "trunk",
    argv: ["build", "--release"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["ok trunk release 0.42s -> dist/index.html"],
    forbiddenMarkers: ["starting build", "INFO", ...NO_OMISSIONS],
  },
  {
    id: "build-mix",
    projection: "build",
    executable: "mix",
    argv: ["compile"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: ["ok mix falryn 42 files"],
    forbiddenMarkers: ["Compiling", "Generated", ...NO_OMISSIONS],
  },
  {
    id: "operation-php",
    projection: "operation",
    executable: "php",
    argv: ["app.php"],
    rtkArgv: ["php", "app.php"],
    requiredMarkers: ["Falryn PHP application result: context ready"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "operation-php-artisan",
    projection: "operation",
    executable: "php",
    argv: ["artisan", "config:cache"],
    rtkArgv: ["php", "artisan", "config:cache"],
    competitiveTarget: "win",
    requiredMarkers: ["ok artisan Configuration cached"],
    forbiddenMarkers: ["INFO", "successfully", ...NO_OMISSIONS],
  },
  {
    id: "operation-php-lint",
    projection: "operation",
    executable: "php",
    argv: ["-l", "app.php"],
    rtkArgv: ["php", "-l", "app.php"],
    competitiveTarget: "tie",
    requiredMarkers: ["ok app.php"],
    forbiddenMarkers: ["No syntax errors", ...NO_OMISSIONS],
  },
  ...["docker", "podman"].flatMap((executable) =>
    [false, true].map(
      (compose) =>
        ({
          id: `build-${executable}${compose ? "-compose" : ""}`,
          projection: "build",
          executable,
          argv: compose ? ["compose", "build"] : ["build", "."],
          ...(executable === "docker"
            ? compose
              ? { baseline: "raw" as const }
              : { rtkArgv: ["docker", "build", "."] }
            : { baseline: "raw" as const }),
          competitiveTarget: "win",
          requiredMarkers:
            executable === "docker"
              ? [
                  compose
                    ? "ok docker services falryn 0.7s builder desktop-linux"
                    : "ok docker docker.io/library/falryn:latest@736abc784def 0.7s builder desktop-linux",
                  "steps 5:",
                ]
              : [
                  compose ? "ok podman services falryn" : "ok podman falryn:latest@736abc784def",
                  "steps 3:",
                ],
          forbiddenMarkers: ["DONE", "STEP 1/", ...NO_OMISSIONS],
        }) as const,
    ),
  ),
  ...[
    ["just", "$ build"],
    ["mise", "[build] $ build"],
    ["task", "task: [build] build"],
    ["make", "make: Entering directory"],
  ].map(
    ([executable, prefix]) =>
      ({
        id: `build-${executable}`,
        projection: "build",
        executable: executable ?? "",
        argv: ["build"],
        baseline: "raw",
        competitiveTarget: "win",
        requiredMarkers: [
          "ok dist/falryn 1.2MB 420ms",
          "steps 3: compile context engine, bundle runtime, write manifest",
        ],
        forbiddenMarkers: [prefix ?? "", "Build step", ...NO_OMISSIONS],
      }) as const,
  ),
  {
    id: "operation-shopify",
    projection: "operation",
    executable: "shopify",
    argv: ["theme", "push"],
    baseline: "raw",
    competitiveTarget: "win",
    requiredMarkers: [
      "ok shopify push falryn-push falryn-store.myshopify.com 42 files",
      "https://falryn-store.myshopify.com?preview_theme_id=736",
    ],
    forbiddenMarkers: ["Uploading", "Theme ", ...NO_OMISSIONS],
  },
  {
    id: "operation-ollama",
    projection: "operation",
    executable: "ollama",
    argv: ["run", "falryn"],
    baseline: "raw",
    requiredMarkers: ["Falryn model response: every required build fact is preserved."],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
  {
    id: "operation-java",
    projection: "operation",
    executable: "java",
    argv: ["-jar", "falryn.jar"],
    baseline: "raw",
    requiredMarkers: ["Falryn Java application: context engine ready"],
    forbiddenMarkers: [...NO_OMISSIONS],
  },
] as const satisfies readonly ProjectionCase[];
