/** Public contracts for this capability. Internal modules import their exact dependencies. */

export type {
  DiagnosticEvent,
  DiagnosticLevel,
  DiagnosticSubsystem,
  DiagnosticsReport,
  DiagnosticValue,
} from "./diagnostics.ts";
export {
  DIAGNOSTIC_LEVELS,
  DIAGNOSTIC_SUBSYSTEMS,
  isDiagnosticSubsystem,
  MAX_DEBUG_PREVIEW_LENGTH,
  MAX_DEBUG_PREVIEWS,
  MAX_DEBUG_WINDOW_MS,
  MAX_DIAGNOSTIC_CARDINALITY,
  MAX_DIAGNOSTIC_METADATA_KEYS,
  MAX_DIAGNOSTIC_VALUE_LENGTH,
  MAX_RETAINED_DIAGNOSTICS,
} from "./diagnostics.ts";
export type {
  ColorLevel,
  FlushReport,
  FlushStatus,
  HandleFacts,
  InputStreamPort,
  ObservedHandles,
  OutputStreamPort,
  RecordingOutputStream,
  RecordingOutputStreamOptions,
  RendererFailure,
  RendererFailureCode,
  StaticInputStreamOptions,
  StdinContent,
  StdinError,
  StreamCapability,
  StreamWrite,
  StreamWriteStatus,
  SymbolSupport,
  TerminalCapabilities,
} from "./terminal.ts";
export {
  COLOR_LEVELS,
  colorLevelFor,
  createRecordingOutputStream,
  createStaticInputStream,
  DEFAULT_STDIN_MAX_BYTES,
  DETACHED_HANDLE,
  DETACHED_HANDLES,
  decodeStdin,
  FLUSH_STATUSES,
  isCompleteFlush,
  isReadableBound,
  MAX_STDIN_BYTES,
  MAX_STREAM_WRITE_BYTES,
  MAX_TERMINAL_COLUMNS,
  MIN_TERMINAL_COLUMNS,
  RENDERER_FAILURE_CODES,
  STDIN_ENCODING,
  STREAM_WRITE_STATUSES,
  SYMBOL_SUPPORTS,
  symbolSupportFor,
  terminalCapabilities,
  terminalSize,
} from "./terminal.ts";
export {
  displayWidth,
  graphemes,
  MAX_DISPLAY_WIDTH,
  sanitizeTerminalText,
  truncateToWidth,
  wordStarts,
  wrapToWidth,
  wrapToWidthWindow,
} from "./text-display.ts";
